input-output-hk/marlowe-cardano

marlowe-actus/src/Language/Marlowe/ACTUS/Domain/ContractState.hs
marlowe-actus/src/Language/Marlowe/ACTUS/Domain/Schedule.hs
marlowe-actus/src/Language/Marlowe/ACTUS/Generator/Analysis.hs
marlowe-playground-server/app/PSGenerator.hs
marlowe-playground-server/src/API.hs
marlowe-playground-server/src/Server.hs

SCP-3014: API function providing cash-flows

---

web-common-marlowe/src/Marlowe/Slot.purs

This is mainly for consistency, to avoid potential problems like in https://github.com/input-output-hk/plutus-apps/pull/77.
- Branch
- PR

Fix Shelley launch date

---

README.adoc

Just wanted to add this command in the readme incase it is useful for future team members who want to run nix on a macOS.
- Branch
- PR

Add notes to 'Nix on macOS' section  of readme about restarting nix daemon after updating the nix.conf file

---

marlowe-dashboard-server/src/Marlowe/Run/Webserver/Wallet/CentralizedTestnet/Server.hs

Fix string annotation

---

marlowe/cli/Language/Marlowe/CLI/Export.hs
marlowe/src/Language/Marlowe/Client.hs
marlowe/src/Language/Marlowe/Scripts.hs
marlowe/test/Spec/Marlowe/AutoExecute.hs
marlowe/test/Spec/Marlowe/Marlowe.hs

1 Ada limit TxOut for Marlowe

---

marlowe-dashboard-client/src/API/Contract.purs

This PR fixes a serialization issue on the response of invokeEndpoint. 
- Branch
- PR

Fix invokeEndpoint decoding

---

marlowe-dashboard-client/webpack.config.js

We don't need HTTPS in dev for Marlowe Run. We only need it in Marlowe Playground for OAuth.
- Branch
- PR

Use HTTP in dev for Marlowe Run

---

marlowe-dashboard-client/spago-packages.nix
marlowe-dashboard-client/src/Capability/Toast.purs
marlowe-dashboard-client/src/Main.purs
marlowe-dashboard-client/src/MainFrame/Lenses.purs
marlowe-dashboard-client/src/MainFrame/State.purs
marlowe-dashboard-client/src/MainFrame/Types.purs
marlowe-dashboard-client/src/MainFrame/View.purs
marlowe-dashboard-client/src/Store.purs
marlowe-dashboard-client/src/Toast/Lenses.purs
marlowe-dashboard-client/src/Toast/State.purs
marlowe-dashboard-client/src/Toast/Types.purs
packages.dhall

- Adds the current toast message to the Store
- Makes Toast its own component that subscribes to the store.
- Branch
- PR

Move Toast State to Store

---

cabal.project

revised url for plutus-apps repo

---

doc/conf.py
doc/marlowe/tutorials/introducing-marlowe.rst
marlowe-dashboard-client/src/Page/Welcome/View.purs

Update some links in the documentation that were pointing to `alpha` and `staging` (which are the same thing) to point to production (https://marlowe-finance.io).
- Branch
- PR

Update links to point to production

---

doc/conf.py
doc/marlowe/tutorials/introducing-marlowe.rst
marlowe-dashboard-client/src/Page/Welcome/View.purs

Update links to point to production (copy of #80)

---

.github/workflows/deploy.yml
scripts/deploy-bitte

add config updates for current sprint env

---

marlowe-cli/src/Language/Marlowe/CLI/Test/Types.hs
marlowe-dashboard-client/src/Capability/PlutusApps/MarloweApp.purs
marlowe-dashboard-client/src/Humanize.purs
marlowe-dashboard-client/src/Marlowe/Execution/State.purs
marlowe-dashboard-client/src/Page/Contract/View.purs
marlowe-playground-client/src/Marlowe/Gen.purs
marlowe-playground-client/src/Marlowe/Holes.purs
marlowe-playground-client/src/Page/Simulation/View.purs
marlowe-playground-client/src/Simulator/State.purs
marlowe-playground-client/src/Simulator/Types.purs
marlowe-playground-client/src/StaticAnalysis/BottomPanel.purs
marlowe-playground-client/test/Marlowe/Holes/SemanticTest.purs
marlowe/src/Language/Marlowe/Analysis/FSSemantics.hs
marlowe/src/Language/Marlowe/Client.hs
marlowe/src/Language/Marlowe/Extended.hs
marlowe/src/Language/Marlowe/Semantics.hs
marlowe/src/Language/Marlowe/SemanticsTypes.hs
web-common-marlowe/src/Marlowe/Semantics.purs

SlotInterval to TimeInterval renaming

---

marlowe/marlowe.cabal
marlowe/src/Language/Marlowe/FindInputs.hs
nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe.nix
nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe.nix
nix/pkgs/haskell/materialized-windows/.plan.nix/marlowe.nix

This PR adds a function that uses static analysis to obtain a list of "unit tests" (lists of transactions) that cover the different branches of the given contract. If static analysis fails it returns a tuple that includes the error by the solver and the offending extension of the contract. Basically, the function just adds `Assert FalseObs` to each of the leaves of the contract (alternatively), and removes any other `Assert`s in the contract
This is the result of applying it to `EscrowSimple` in `marlowe` repo (plus manual formatting):
```haskell
>>> import Language.Marlowe.Examples.EscrowSimple
>>> getAllInputs contract
Right [ (0, [ TransactionInput {txInterval = SlotInterval 10 10, txInputs = []}
])
, (0, [ TransactionInput {txInterval = SlotInterval 0 0, txInputs = [NormalInput …
```

SCP-3558 - Function to generate valid inputs for contract

---

cabal.project

Attempt to fix nix dlopen/fork errors in CI.

Reverted plutus-apps.

---

marlowe-playground-client/src/Component/Demos/View.purs
marlowe-playground-client/src/Home.purs
marlowe-playground-client/src/MainFrame/View.purs
marlowe-playground-client/src/Page/JavascriptEditor/View.purs

SCP3484 modify accessibility roles and labels for testing

---

marlowe/src/Language/Marlowe/Scripts.hs

Enforce single Marlowe input and output

---

default.nix
marlowe-dashboard-client/README.md
marlowe-dashboard-client/arion-compose.nix
marlowe-dashboard-client/dev/marlowe-run.nix
marlowe-dashboard-client/dev/node-config.nix
marlowe-dashboard-client/dev/pab-config.nix
marlowe-dashboard-client/src/Component/ContractPreview/View.purs
marlowe-dashboard-client/src/Marlowe/Execution/State.purs
marlowe-dashboard-client/src/Marlowe/Execution/Types.purs
marlowe-dashboard-client/src/Page/Dashboard/State.purs
marlowe-dashboard-client/src/Page/Dashboard/Types.purs
marlowe-dashboard-client/src/Page/Dashboard/View.purs
marlowe-dashboard-client/src/Store/Contracts.purs
marlowe-dashboard-client/test/Marlowe/Execution.purs
nix/dev/scripts.nix
nix/pkgs/default.nix
shell.nix

This PR fixes the development environment for Mac users using the development network.
- Branch
- PR

SCP-3850 fix dev env for osx

---

marlowe-dashboard-client/src/Component/Toast/View.purs

What the title says
- Branch
- PR

SCP-3970 Fix confirm button being blocked by toast

---

marlowe-playground-client/src/Blockly/DateTimeField.js
marlowe-playground-client/src/Blockly/Internal.js
marlowe-playground-client/src/Blockly/Internal.purs
marlowe-playground-client/src/Component/Blockly/State.purs
marlowe-playground-client/src/Component/Blockly/Types.purs
marlowe-playground-client/src/Component/DateTimeLocalInput/State.purs
marlowe-playground-client/src/Marlowe/Blockly.purs
marlowe-playground-client/src/Page/BlocklyEditor/State.purs
marlowe-playground-client/src/Page/BlocklyEditor/View.purs
marlowe-playground-client/test/Blockly/Headless.js
marlowe-playground-client/test/Component/DateTimeLocalInputTest.purs
marlowe-playground-client/test/Main.purs

This PR adds a DateTime picker to Blockly to be able to select constant times
Can be previewed at https://marlowe-playground-hernan.plutus.aws.iohkdev.io/
- Branch
- PR

SCP-3912 add blockly datetime picker

---

marlowe-dashboard-client/src/Page/Welcome/View.purs

Just updated the video: https://www.youtube.com/embed/-yBDz_MeWXw
- PR

SCP-3998 - Update Marlowe Run intro video

---

marlowe-playground-client/src/Component/DateTimeLocalInput/State.purs
marlowe-playground-client/src/Component/DateTimeLocalInput/Types.purs
marlowe-playground-client/src/MainFrame/State.purs
marlowe-playground-client/src/Page/BlocklyEditor/State.purs
marlowe-playground-client/src/Page/HaskellEditor/State.purs
marlowe-playground-client/src/Page/JavascriptEditor/State.purs
marlowe-playground-client/src/Page/MarloweEditor/State.purs
marlowe-playground-client/src/Page/Simulation/State.purs
marlowe-playground-client/src/Simulator/State.purs
web-common-marlowe/src/Marlowe/Template.purs

This PR adds a similar mechanism than the simulator uses for setting the default time parameters to be 5 minute appart from each other.
- Branch
- PR

SCP-4056: fix default time metadata in static analysis

---

marlowe-playground-client/src/StaticAnalysis/BottomPanel.purs

This PR solves the issue of just showing a contract Path on the static analysis, which was confusing
Now it is a little clearer
But sadly it is not easy in the Static Analysis context to point to the code (because of the Haskell and JS nature). But if you go to the warning tabs in Blockly or Marlowe you can select the block or see it highlighted 
- Branch
- PR

SCP 4069 - pretty print contract path

---

marlowe-playground-client/generated/Examples/Haskell/Contracts.purs
marlowe-playground-client/generated/Examples/Marlowe/Contracts.purs
marlowe-playground-client/src/Examples/JS/Contracts.purs
marlowe-playground-client/test/Marlowe/ContractTests.purs
marlowe-playground-client/test/Marlowe/DeinstantiatorTests.purs
marlowe-playground-server/contracts/Escrow.hs
web-common-marlowe/src/Examples/PureScript/Escrow.purs

Small fix in the naming of parameters for Escrow

Fix template parameter order for Escrow example

---

marlowe-runtime/docs/filtered-chain-sync-spec-1.0.md

Adds draft spec for filtered chain sync protocol to be implemented by Marlowe Runtime Chain Index.

SCP-4247 Filtered Chain Sync Protocol specification

---

marlowe-contracts/test/Spec/Marlowe/Contracts.hs
marlowe/src/Language/Marlowe/Analysis/FSSemantics.hs
marlowe/src/Language/Marlowe/Core/V1/Semantics.hs
marlowe/test/Spec/Marlowe/Marlowe.hs
marlowe/test/Spec/Marlowe/Semantics.hs
marlowe/test/Spec/Marlowe/Util.hs
web-common-marlowe/src/Language/Marlowe/Core/V1/Semantics.purs

Change implementation of DivValue to round towards zero
- Branch
- PR

SCP-4331 - Make Division More Usable

---

marlowe/src/Language/Marlowe/Client.hs

This PR is a rebase of PR #181 to the latest `main`. See the discussion there.
- Branch
- PR

Successor to PR181

---

marlowe-actus/actus-core/src/Actus/Core.hs
marlowe-actus/actus-core/src/Actus/Domain.hs
marlowe-actus/actus-core/src/Actus/Domain/ContractTerms.hs
marlowe-actus/actus-core/src/Actus/Model.hs
marlowe-actus/actus-core/src/Actus/Model/ContractSchedule.hs
marlowe-actus/actus-core/src/Actus/Model/Payoff.hs
marlowe-actus/actus-core/src/Actus/Model/StateTransition.hs
marlowe-actus/actus-core/test/Spec.hs
marlowe-actus/actus-core/test/Spec/TestFramework.hs
marlowe-actus/src/Actus/Marlowe.hs
marlowe-actus/test/Spec/Actus/Examples.hs

This PR adds the ACTUS contract type `SWAPS`. This contract type represents a generic swap, where the two legs are defined by other ACTUS contracts. 
- Branch
- PR

SCP-4374: ACTUS contract type SWAPS

---

marlowe-runtime/marlowe-runtime.cabal
marlowe-runtime/src/Language/Marlowe/Protocol/Sync/Client.hs
nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-runtime.nix
nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-runtime.nix
nix/pkgs/haskell/materialized-windows/.plan.nix/marlowe-runtime.nix

- Made new data and GADT definitions
- Implemented the Client hoist functions
- Implemented the Client peer functions
- Changed blockHeader* to header* for consistency
- Updated updateMaterialized

Implemented the typed-protocols Marlowe Sync client

---

marlowe-chain-sync/src/Language/Marlowe/Runtime/ChainSync/Api.hs
marlowe-chain-sync/src/Language/Marlowe/Runtime/ChainSync/Database/PostgreSQL.hs
marlowe-runtime/marlowe-tx/Main.hs
marlowe-runtime/src/Language/Marlowe/Runtime/History/Follower.hs
marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/Api.hs
marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/Submit.hs
marlowe-runtime/test/Language/Marlowe/Runtime/History/FollowerSpec.hs

Adds an implementation for the `SubmitJob` that delegates to chain seek (both for submitting the tx and awaiting the block).

SCP4448 Runtime Tx Submission

---

cabal.project
marlowe-chain-sync/marlowe-chain-sync.cabal
marlowe-chain-sync/src/Language/Marlowe/Runtime/Cardano/Api.hs
marlowe-chain-sync/src/Language/Marlowe/Runtime/ChainSync/Api.hs
marlowe-chain-sync/src/Language/Marlowe/Runtime/ChainSync/Database.hs
marlowe-chain-sync/src/Language/Marlowe/Runtime/ChainSync/Database/PostgreSQL.hs
marlowe-chain-sync/src/Language/Marlowe/Runtime/ChainSync/QueryServer.hs
marlowe-chain-sync/src/Language/Marlowe/Runtime/Plutus/V2/Api.hs
marlowe-runtime/cli/Language/Marlowe/Runtime/CLI/Command/Apply.hs
marlowe-runtime/marlowe-runtime.cabal
marlowe-runtime/marlowe-tx/Main.hs
marlowe-runtime/src/Language/Marlowe/Runtime/Core/Api.hs
marlowe-runtime/src/Language/Marlowe/Runtime/Plutus/V2/Contexts.hs
marlowe-runtime/src/Language/Marlowe/Runtime/Plutus/V2/Scripts.hs
marlowe-runtime/src/Language/Marlowe/Runtime/Plutus/V2/Scripts/MarloweV1/RoleTokensPolicy.hs
marlowe-runtime/src/Language/Marlowe/Runtime/Plutus/V2/Scripts/MarloweV1/RoleTokensPolicy/Types.hs
marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/Api.hs
marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/BuildConstraints.hs
marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/Constraints.hs
marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/Query.hs
marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/Server.hs
marlowe-runtime/test/Language/Marlowe/Runtime/History/FollowerSpec.hs
marlowe-runtime/test/Language/Marlowe/Runtime/History/Script.hs
marlowe-runtime/test/Language/Marlowe/Runtime/Transaction/BuildConstraintsSpec.hs
nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-chain-sync.nix
nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-runtime.nix
nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-chain-sync.nix
nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-runtime.nix
nix/pkgs/haskell/materialized-windows/.plan.nix/marlowe-chain-sync.nix
nix/pkgs/haskell/materialized-windows/.plan.nix/marlowe-runtime.nix

SCP-4441, SCP-4283 - apply inputs and create contract constraints

---

dev-shell.nix
marlowe-cli/flake.lock
marlowe-cli/flake.nix
packages.nix

SCP-4484 Added runtime components to flake develop shell.

---

marlowe-chain-sync/src/Language/Marlowe/Runtime/ChainSync/Api.hs
marlowe-runtime/cli/Language/Marlowe/Runtime/CLI/Command.hs
marlowe-runtime/cli/Language/Marlowe/Runtime/CLI/Command/Create.hs
marlowe-runtime/cli/Language/Marlowe/Runtime/CLI/Command/Submit.hs
marlowe-runtime/cli/Language/Marlowe/Runtime/CLI/Command/Tx.hs
marlowe-runtime/cli/Language/Marlowe/Runtime/CLI/Command/Withdraw.hs
marlowe-runtime/config/Language/Marlowe/Runtime/CLI/Option.hs
marlowe-runtime/marlowe-runtime.cabal
marlowe-runtime/src/Language/Marlowe/Runtime/Core/Api.hs
marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/Api.hs
marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/BuildConstraints.hs
marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/Server.hs
nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-runtime.nix
nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-runtime.nix
nix/pkgs/haskell/materialized-windows/.plan.nix/marlowe-runtime.nix

SCP-4487 - implement missing transaction management pieces in `marlowe` cli tool

---

marlowe-runtime/examples/.gitignore
marlowe-runtime/examples/.ipynb_checkpoints/runtime-actus-pam-checkpoint.ipynb
marlowe-runtime/examples/create.ipynb
marlowe-runtime/examples/create.sh
marlowe-runtime/examples/history.ipynb
marlowe-runtime/examples/history.sh
marlowe-runtime/examples/runtime-actus-pam.ipynb
marlowe-runtime/examples/runtime-actus-pam.sh
marlowe-runtime/examples/submit.ipynb
marlowe-runtime/examples/submit.sh

Work in progress.
- Branch
- PR

SCP-4484 Jupyter Notebooks for Marlowe Runtime Testing

---

marlowe-chain-sync/src/Language/Marlowe/Runtime/ChainSync/Api.hs
marlowe-runtime/cli/Language/Marlowe/Runtime/CLI/Command/Apply.hs
marlowe-runtime/cli/Language/Marlowe/Runtime/CLI/Command/Log.hs
marlowe-runtime/cli/Language/Marlowe/Runtime/CLI/Command/Submit.hs
marlowe-runtime/cli/Language/Marlowe/Runtime/CLI/Command/Tx.hs
marlowe-runtime/cli/Language/Marlowe/Runtime/CLI/Command/Withdraw.hs
marlowe-runtime/config/Language/Marlowe/Runtime/CLI/Option.hs
marlowe-runtime/logging/Language/Marlowe/Runtime/Logging.hs
marlowe-runtime/marlowe-runtime.cabal
marlowe-runtime/marlowe-tx/Main.hs
marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/Constraints.hs
marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/Server.hs
nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-runtime.nix
nix/pkgs/haskell/materialized-darwin/default.nix
nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-runtime.nix
nix/pkgs/haskell/materialized-linux/default.nix
nix/pkgs/haskell/materialized-windows/.plan.nix/marlowe-runtime.nix
nix/pkgs/haskell/materialized-windows/default.nix

Implement `marlowe apply` and add some logging config pieces

---

marlowe-cli/src/Language/Marlowe/CLI/Transaction.hs
marlowe-runtime/src/Language/Marlowe/Runtime/Core/ScriptRegistry.hs

Update registry for Marlowe Runtime with reference scripts on `preprod` and `mainnet`.
- Branch
- PR

SCP-4527 Published validator reference scripts.

---

marlowe-runtime/examples/.gitignore
marlowe-runtime/examples/create.ipynb
marlowe-runtime/examples/create.sh

Successfully ran `marlowe create` on the Actus PAM contract.
- Branch
- PR

SCP-4484 Updated notebook for `marlowe create`.

---

marlowe-runtime/marlowe-tx/Main.hs

SCP-4259 - Fix `marlowe-history` server config in `marlowe-tx`

---

marlowe-cli/.gitignore
marlowe-runtime/examples/runtime-close.ipynb

[This test case](https://github.com/input-output-hk/marlowe-cardano/blob/SCP-4484/marlowe-runtime/examples/runtime-close.ipynb) fails on `mainnet` with an unusual time-related error.
- Branch
- PR

SCP-4484 Failing test case for `close` on `mainnet`.

---

marlowe-runtime/src/Language/Marlowe/Runtime/Core/ScriptRegistry.hs

The `preprod` network was respun, so we needed to re-publish the reference scripts for the Marlowe validators there.
- Branch
- PR

SCP-4567 Published reference scripts for respun `preprod` testnet.

---

marlowe-cli/flake.lock

Added a `flake.lock` in `marlowe-cli` so that the correct version of `jupyterWith` is found.
- Branch
- PR

SCP-4595 Fixed lock for for Jupyter notebooks.

---

marlowe-runtime/examples/choose.ipynb
marlowe-runtime/examples/choose.sh
marlowe-runtime/examples/notify.ipynb
marlowe-runtime/examples/notify.sh

Created Jupyter notebooks and `bash` scripts for `marlowe choose` and `marlowe notify`.
- Branch
- PR

SCP-4596 SCP-4597 Tests of `choose` and `notify` in Marlowe Runtime

---

marlowe-runtime/src/Language/Marlowe/Runtime/Plutus/V2/Contexts.hs
marlowe-runtime/src/Language/Marlowe/Runtime/Plutus/V2/Scripts/MarloweV1/RoleTokensPolicy.hs
marlowe-runtime/src/Language/Marlowe/Runtime/Plutus/V2/Scripts/MarloweV1/RoleTokensPolicy/Types.hs
marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/Api.hs
marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/BuildConstraints.hs
marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/Constraints.hs

This is work for both SCP-4571 and SCP-4613, related to contracts with role tokens. Made a PR so we can share code as this is worked on.

Scp 4571 role tokens constraints work

---

marlowe-cli/flake.lock
marlowe-runtime/examples/roles.ipynb

I wanted to update the roles Jupyter notebook. Unsure about the `flake.lock` change but it always changes when I start the notebook server on my system.

SCP-4623 Updated roles notebook to reflect recent fixes

---

marlowe-runtime/src/Language/Marlowe/Runtime/Core/ScriptRegistry.hs

Tested manually.
- Branch
- PR

SCP-4568 Updated script registry for respun `preview` network.

---

marlowe-cli/cookbook/repair.ipynb
marlowe-cli/flake.lock
marlowe-cli/flake.nix
marlowe-cli/src/Language/Marlowe/CLI/Analyze.hs

SCP-4617 Create tutorial for `marlowe-cli run analyze`

---

flake.lock

Updates the cardano-world flake input with the respun preview network.

Update cardano-world flake

---

marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/Api.hs
marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/Server.hs
marlowe-runtime/web-server-test/Spec.hs
marlowe-runtime/web-server/Language/Marlowe/Runtime/Web/Server.hs
marlowe-runtime/web-server/Language/Marlowe/Runtime/Web/Server/DTO.hs
marlowe-runtime/web-server/Language/Marlowe/Runtime/Web/Server/Monad.hs
marlowe-runtime/web-server/Language/Marlowe/Runtime/Web/Server/REST/Contracts.hs
marlowe-runtime/web-server/Language/Marlowe/Runtime/Web/Server/REST/Transactions.hs
marlowe-runtime/web-server/Language/Marlowe/Runtime/Web/Server/TxClient.hs
marlowe-runtime/web-server/Language/Marlowe/Runtime/Web/Server/Util.hs
marlowe-runtime/web/Language/Marlowe/Runtime/Web/API.hs
marlowe-runtime/web/Language/Marlowe/Runtime/Web/Types.hs

This is the endpoint which allows clients to submit a signed creation transaction.

SCP-4706 PUT /contracts/:contractId

---

flake.lock
flake.nix
nix/tullia.nix

feat: setup cicero ci actions

---

marlowe-chain-sync/app/Main.hs
marlowe-chain-sync/src/Language/Marlowe/Runtime/ChainSync.hs
marlowe-chain-sync/src/Language/Marlowe/Runtime/ChainSync/Database.hs
marlowe-chain-sync/src/Language/Marlowe/Runtime/ChainSync/Database/PostgreSQL.hs
marlowe-chain-sync/src/Language/Marlowe/Runtime/ChainSync/NodeClient.hs

SCP-4530 Cannot find block

---

marlowe-cli/flake.lock
marlowe-cli/flake.nix
marlowe-runtime/examples/runtime-close.ipynb

This commit documents the test of the Marlowe Runtime backend on `mainnet`.
- Branch
- PR

SCP-4743 Test of Marlowe Runtime on mainnet

---

marlowe-runtime/marlowe-runtime.cabal
marlowe-runtime/web-server-app/Main.hs
marlowe-runtime/web-server-app/Options.hs
marlowe-runtime/web-server/Language/Marlowe/Runtime/Web/Server.hs
nix/dev/compose.nix
nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-runtime.nix
nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-runtime.nix

Scp 4750 add cors header

---

nix/dev/compose.nix
scripts/local-docker.env

Minor Docker improvements

---

marlowe-runtime/marlowe-runtime.cabal
marlowe-runtime/web-server/Language/Marlowe/Runtime/Web/Server.hs
nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-runtime.nix
nix/pkgs/haskell/materialized-darwin/default.nix
nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-runtime.nix
nix/pkgs/haskell/materialized-linux/default.nix

Scp 4750 improve cors handling by using wai-cors

---

marlowe-apps/src/Language/Marlowe/Runtime/App/Transact.hs

- Branch
- [] Tests are provided (if possible)
- PR

SCP-4846 SCP-4847 Adjusted exports in `marlowe-apps`.

---

marlowe-runtime/test/Language/Marlowe/Runtime/Transaction/ConstraintsSpec.hs

As part of this work some set-up code is now shared from prior tests.

SCP-4803 selectCoins creates a balanceable tx test working

---

marlowe/best-practices.md
marlowe/test/ReadMe.md

Created [a single markdown page](https://github.com/input-output-hk/marlowe-cardano/blob/SCP-4476/marlowe/best-practices.md) that documents the best practices for using Marlowe on the Cardano blockchain. This document is designed for an audience that is already thoroughly familiar with the Marlowe DSL and has some experience running Marlowe on the Cardano blockchain.
I plan to merge this document into `main` on January 6.
- Branch
- PR

SCP-4476 Drafted documentation of best practices and limitations.

---

CONTRIBUTING.adoc

This adds text describing the MIP process to the CONTRIBUTING document.
- Branch
- PR

SCP-4683 Added MIP text to contributing doc.

---

marlowe-test/chain/ReadMe.md
marlowe-test/chain/compare.sql

SCP-4772 Fixed botched rebase of db comparison

---

marlowe-runtime/history/Language/Marlowe/Runtime/History/SyncServer.hs

This will be covered by planned upcoming integration tests.

SCP-4838 `marlowe log --tail` does not follow contract

---

flake.nix
marlowe-runtime/doc/deployment.md
marlowe-runtime/doc/marlowe-indexer.md
marlowe-runtime/doc/marlowe-sync.md
marlowe-runtime/history-api/Language/Marlowe/Runtime/History/Api.hs
marlowe-runtime/marlowe-runtime.cabal
marlowe-runtime/marlowe-sync/Logging.hs
marlowe-runtime/marlowe-sync/Main.hs
marlowe-runtime/sync/Language/Marlowe/Runtime/Sync.hs
marlowe-runtime/sync/Language/Marlowe/Runtime/Sync/Database.hs
marlowe-runtime/sync/Language/Marlowe/Runtime/Sync/Database/PostgreSQL.hs
marlowe-runtime/sync/Language/Marlowe/Runtime/Sync/Database/PostgreSQL/GetCreateStep.hs
marlowe-runtime/sync/Language/Marlowe/Runtime/Sync/Database/PostgreSQL/GetIntersectionForContract.hs
marlowe-runtime/sync/Language/Marlowe/Runtime/Sync/Database/PostgreSQL/GetNextSteps.hs
marlowe-runtime/sync/Language/Marlowe/Runtime/Sync/Database/PostgreSQL/GetTipForContract.hs
marlowe-runtime/sync/Language/Marlowe/Runtime/Sync/MarloweSyncServer.hs
nix/dev/compose.nix
nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-runtime.nix
nix/pkgs/haskell/materialized-darwin/default.nix
nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-runtime.nix
nix/pkgs/haskell/materialized-linux/default.nix
packages.nix
scripts/local-docker.env

As a user of `marlowe-sync`, I want it to support the `MarloweSync` protocol so that existing clients of `marlowe-history` can easily switch to using `marlowe-sync`.

SCP-4874 MarloweSync Server

---

marlowe-runtime/marlowe-runtime.cabal
marlowe-runtime/test/Language/Marlowe/Runtime/Transaction/ConstraintsSpec.hs
nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-runtime.nix
nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-runtime.nix

I figured out what was wrong with my test TxBodyContent (it wasn't empty enough to begin with). We can discuss if this test seems like it's doing enough.

Scp 4677 QC test for balanceTx

---

marlowe-runtime/test/Language/Marlowe/Runtime/Transaction/ConstraintsSpec.hs

Found some code where the comments state some ADA will be generated but in fact we were using a static value every time!

Fixed code where a generator should have been used

---

.github/workflows/test.yml
cardano-integration/src/Test/Integration/Workspace.hs
marlowe-runtime/indexer/Language/Marlowe/Runtime/Indexer/ChainSeekClient.hs
marlowe-runtime/indexer/Language/Marlowe/Runtime/Indexer/Database.hs
marlowe-runtime/indexer/Language/Marlowe/Runtime/Indexer/Database/PostgreSQL/GetMarloweUTxO.hs

Migrated these commits over from #449 so that their being merged isn't blocked by that PR

Fix integration test

---

marlowe-integration/src/Test/Integration/Marlowe/Local.hs
marlowe-runtime/marlowe-runtime.cabal
marlowe-runtime/marlowe-tx/Main.hs
marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Submit.hs
nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-runtime.nix
nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-runtime.nix

Improve Integration Test Stability

---

marlowe-test/stress-testing.md

This PR adds a document summarizing the techniques and tools for performing stress testing of Marlowe Runtime.
- Branch
- PR

SCP-4980 Documented stress testing for Marlowe Runtime.

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.adoc

This PR adds reviewing criteria to the template for pull requests.

SCP-5043 Reviewing criteria for PRs.

---

marlowe-runtime/indexer/Language/Marlowe/Runtime/Indexer/ChainSeekClient.hs

We previously loaded the `EraHistory` once on startup in `marlowe-indexer`, but that was a mistake because the era history changes every epoch as the safe zone is extended. Now it always loads a fresh copy from `chainseekd` when it needs it.

Reload EraHistory in `marlowe-indexer`

---

marlowe-runtime/marlowe-runtime.cabal
marlowe-runtime/sync-api/Language/Marlowe/Protocol/Query/Client.hs
marlowe-runtime/sync-api/Language/Marlowe/Protocol/Query/Codec.hs
marlowe-runtime/sync-api/Language/Marlowe/Protocol/Query/Server.hs
marlowe-runtime/sync-api/Language/Marlowe/Protocol/Query/Types.hs
marlowe-runtime/sync/Language/Marlowe/Runtime/Sync/Database.hs
marlowe-runtime/sync/Language/Marlowe/Runtime/Sync/Database/PostgreSQL.hs
marlowe-runtime/sync/Language/Marlowe/Runtime/Sync/Database/PostgreSQL/GetWithdrawal.hs
marlowe-runtime/sync/Language/Marlowe/Runtime/Sync/Database/PostgreSQL/GetWithdrawals.hs
marlowe-runtime/sync/Language/Marlowe/Runtime/Sync/QueryServer.hs
marlowe-runtime/test/Language/Marlowe/Protocol/QuerySpec.hs
nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-runtime.nix
nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-runtime.nix

Added both single and by-contract queries in one PR.

SCP-4994 get withdrawal(s)

---

marlowe-integration-tests/marlowe-integration-tests.cabal
marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/Common.hs
marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/MarloweQuery.hs
marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/StandardContract.hs
marlowe-integration-tests/test/Language/Marlowe/Runtime/IntegrationSpec.hs
marlowe-integration/src/Test/Integration/Marlowe/Local.hs
marlowe-protocols/src/Network/Protocol/Driver.hs
marlowe-runtime/sync-api/Language/Marlowe/Protocol/Query/Types.hs
marlowe-runtime/sync/Language/Marlowe/Runtime/Sync/Database/PostgreSQL/GetHeaders.hs
marlowe-runtime/sync/Language/Marlowe/Runtime/Sync/Database/PostgreSQL/GetTransaction.hs
marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Server.hs
nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-integration-tests.nix
nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-integration-tests.nix

Added full test coverage of all `MarloweQuery` queries, and fixed some bugs that were found along the way.
- Branch
- PR

Scp 5076 query tests

---

marlowe-chain-sync/example-client/Main.hs
marlowe-protocols/src/Network/Protocol/Driver.hs

SCP-5045 `marlowe-sync` crashes with too many open files

---

.github/PULL_REQUEST_TEMPLATE.md

Simple fix of indentation in markdown.
- Branch
- PR

SCP-5043 Fixed indentation in PR template.

---

marlowe-apps/src/Language/Marlowe/Runtime/App/Parser.hs
marlowe-apps/src/Language/Marlowe/Runtime/App/Types.hs

One more environment variable needed fixing.
- Branch
- PR

SCP-4532 Fixed environment variable name for `marlowe-apps`.

---

ci.nix
deploy/nomadTasks.nix
deploy/oci-images.nix
deploy/operables.nix
marlowe-runtime/web-server-app/Options.hs
nix/dev/compose.nix

Update Operables and OCI Images

---

marlowe-runtime/web-server/Language/Marlowe/Runtime/Web/Server/REST/Contracts.hs
marlowe-runtime/web/Language/Marlowe/Runtime/Web/API.hs
marlowe-runtime/web/Language/Marlowe/Runtime/Web/Client.hs

Let's expose `transactions` link on the `ContractHeader` level to avoid extra queries.
- Branch
- PR

SCP-5094 - Expose "transactions" link on the ````ContractHeader level

---

marlowe-runtime/marlowe-runtime.cabal
marlowe-runtime/web-server/Language/Marlowe/Runtime/Web/Server.hs
marlowe-runtime/web-server/Language/Marlowe/Runtime/Web/Server/DTO.hs
marlowe-runtime/web-server/Language/Marlowe/Runtime/Web/Server/REST/ApiError.hs
marlowe-runtime/web-server/Language/Marlowe/Runtime/Web/Server/REST/Contracts.hs
marlowe-runtime/web-server/Language/Marlowe/Runtime/Web/Server/REST/Transactions.hs
nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-runtime.nix
nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-runtime.nix

Really simple approach to error reporting which gonna allow to iterate much easier when implementing clients.
- Branch
- PR

SCP-5090 structured rest errors

---

marlowe-integration-tests/marlowe-integration-tests.cabal
marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/Common.hs
marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/GetContracts.hs
marlowe-integration-tests/test/Language/Marlowe/Runtime/WebSpec.hs
marlowe-runtime/marlowe-runtime.cabal
marlowe-runtime/web-server/Language/Marlowe/Runtime/Web/Server/DTO.hs
marlowe-runtime/web/Language/Marlowe/Runtime/Web/Client.hs
marlowe-runtime/web/Language/Marlowe/Runtime/Web/Types.hs
nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-integration-tests.nix
nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-runtime.nix
nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-integration-tests.nix
nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-runtime.nix

Set up for Web API end to end test and implementation of get contracts test.
- Branch
- PR

SCP-5023 E2E web api test for get contracts

---

marlowe-integration-tests/marlowe-integration-tests.cabal
marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/Basic.hs
marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/Common.hs
marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/MarloweQuery.hs
marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/StandardContract.hs
marlowe-integration/src/Test/Integration/Marlowe/Local.hs
nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-integration-tests.nix
nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-integration-tests.nix

Includes a minimal changeset to port the integration tests to `marlowe-proxy` from individual services.
- Branch
- PR

SCP-5011 Refactor integration tests to use marlowe-proxy

---

.gitignore
hie.yaml

Adds this important file to the repo so that we all use the same cradle file to reduce discrepancies in development environments.

Commit hie.yaml

---

marlowe-runtime-web/marlowe-runtime-web.cabal
marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server.hs
marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/DTO.hs
marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/Monad.hs
marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/REST.hs
marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/REST/ApiError.hs
marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/REST/Withdrawals.hs
marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/SyncClient.hs
marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/TxClient.hs
marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/API.hs
marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/Client.hs
marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/Types.hs
marlowe-runtime-web/test/Spec.hs
nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-runtime-web.nix
nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-runtime-web.nix

Adds the full REST API for withdrawals (`GET` (all), `GET` (one), `POST`, `PUT`)
- Branch
- PR

SCP-[4711..4714] Withdrawals REST API

---

cardano-integration/src/Test/Integration/Cardano/Process.hs
dev-shell.nix
marlowe-integration-tests/marlowe
marlowe-integration-tests/marlowe-integration-tests.cabal
marlowe-integration-tests/test/Language/Marlowe/Runtime/CliSpec.hs
marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/Common.hs
marlowe-integration/src/Test/Integration/Marlowe/Local.hs
marlowe-protocols/src/Network/Protocol/Connection.hs
nix/dev/scripts.nix
nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-integration-tests.nix
nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-integration-tests.nix
packages.nix
scripts/local-docker.env

This PR sets up code for running the Marlowe Runtime CLI and comparing its output with the `JobClient` mechanism. It implements few meaningful tests.
- Branch
- PR

SCP-5032: Setup CLI E2E Tests infrastructure

---

marlowe-cli/ReadMe.md

Suggesting that we delete a duplicated section on low-level commands.

Update Marlowe-CLI ReadMe.md

---

cabal.project

Remove some constraints and justify other ones.
- Branch
- PR

Use plutus-apps packages from CHaP

---

async-components/async-components.cabal
async-components/src/Control/Concurrent/Component/Probes.hs
deploy/nomadTasks.nix
deploy/operables.nix
marlowe-chain-sync/chain-indexer/Language/Marlowe/Runtime/ChainIndexer.hs
marlowe-chain-sync/chain-indexer/Language/Marlowe/Runtime/ChainIndexer/NodeClient.hs
marlowe-chain-sync/chain-indexer/Language/Marlowe/Runtime/ChainIndexer/Store.hs
marlowe-chain-sync/libchainsync/Language/Marlowe/Runtime/ChainSync.hs
marlowe-chain-sync/marlowe-chain-indexer/Main.hs
marlowe-chain-sync/marlowe-chain-indexer/Options.hs
marlowe-chain-sync/marlowe-chain-sync/Main.hs
marlowe-chain-sync/marlowe-chain-sync/Options.hs
marlowe-integration/src/Test/Integration/Marlowe/Local.hs
marlowe-runtime/indexer/Language/Marlowe/Runtime/Indexer.hs
marlowe-runtime/indexer/Language/Marlowe/Runtime/Indexer/ChainSeekClient.hs
marlowe-runtime/marlowe-indexer/Main.hs
marlowe-runtime/marlowe-proxy/Main.hs
marlowe-runtime/marlowe-sync/Main.hs
marlowe-runtime/marlowe-tx/Main.hs
marlowe-runtime/proxy/Language/Marlowe/Runtime/Proxy.hs
marlowe-runtime/sync/Language/Marlowe/Runtime/Sync.hs
marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction.hs
marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Chain.hs
scripts/local-docker.env

Adds HTTP startup, liveness, and readiness probes to all runtime services.
- Branch
- PR

Add healthchecks to all services

---

marlowe-cli/src/Language/Marlowe/CLI/Analyze.hs

`marlowe-cli run analyze` now consolidates outputs to the same address when it sets up a mock `ScriptContext.
- Branch
- PR

PLT-4207 Consolidates payouts to same address in analysis.

---

marlowe-cli/src/Language/Marlowe/CLI/Run.hs

The stake address for the Marlowe validator is now used when creating transactions with `marlowe-cli run initialize --stake-address`. Previously, `--state-address` had been ignored if a reference script was being used.
- Branch
- PR

SCP-5083 Fixed inclusion of stake address in marlowe address.

---

.github/workflows/deploy.yml
ci.nix
deploy/nomadTasks.nix
deploy/oci-images.nix
deploy/operables.nix
marlowe-protocols/marlowe-protocols.cabal

Setup up automatic deployment on all pushes to `main`:
- Branch
- PR

Deploy runtime from main and publish to GitHub container registry

---

marlowe-runtime/doc/resources.md

This document summarizes the information benchmarking of the three public networks. See https://github.com/input-output-hk/marlowe-cardano/blob/PLT-3566/marlowe-runtime/doc/resources.md.
- Branch
- PR

PLT-3566 Summized resources for running Marlowe Runtime.

---

marlowe-cli/src/Language/Marlowe/CLI/Command.hs
marlowe-cli/src/Language/Marlowe/CLI/Command/Contract.hs
marlowe-cli/src/Language/Marlowe/CLI/Command/Parse.hs
marlowe-cli/src/Language/Marlowe/CLI/Command/Role.hs
marlowe-cli/src/Language/Marlowe/CLI/Command/Run.hs
marlowe-cli/src/Language/Marlowe/CLI/Command/Test.hs
marlowe-cli/src/Language/Marlowe/CLI/Command/Transaction.hs
marlowe-cli/src/Language/Marlowe/CLI/Command/Util.hs
marlowe-cli/src/Language/Marlowe/CLI/Run.hs
marlowe-runtime/src/Language/Marlowe/Runtime/Core/ScriptRegistry.hs
marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Server.hs

Enabled `mainnet` for `marlowe-cli` and `marlowe` tools.
- Branch
- PR

PLT-3880 Enable `mainnet`.

---

.github/workflows/nightly.yml
marlowe-apps/finder/Main.hs
marlowe-apps/marlowe-apps.cabal
marlowe-apps/oracle/Language/Marlowe/Oracle/Process.hs
marlowe-apps/oracle/Main.hs
marlowe-apps/scaling/Main.hs
marlowe-apps/src/Language/Marlowe/Runtime/App/Channel.hs
marlowe-apps/src/Language/Marlowe/Runtime/App/Stream.hs
scripts/setup-dev-connection
test-wallets/test.0.addr
test-wallets/test.1.addr
test-wallets/test.10.addr
test-wallets/test.11.addr
test-wallets/test.12.addr
test-wallets/test.13.addr
test-wallets/test.14.addr
test-wallets/test.15.addr
test-wallets/test.16.addr
test-wallets/test.17.addr
test-wallets/test.18.addr
test-wallets/test.19.addr
test-wallets/test.2.addr
test-wallets/test.3.addr
test-wallets/test.4.addr
test-wallets/test.5.addr
test-wallets/test.6.addr
test-wallets/test.7.addr
test-wallets/test.8.addr
test-wallets/test.9.addr

Adds a nightly test workflow. In support of this, the following code changes have been made:
Future work:
- Collect status on failure rate of `marlowe-scaling`
- Validator tests (Requires different infrastructure setup - not runtime related)
- Scenario-based tests on public testnets
- Benchmarking sync times.
- Branch
- PR

PLT-4246 Nightly tests

---

marlowe-chain-sync/src/Language/Marlowe/Runtime/ChainSync/Api.hs
marlowe-integration-tests/test/Language/Marlowe/Runtime/CliSpec.hs
marlowe-runtime-cli/app/Language/Marlowe/Runtime/CLI/Command/Create.hs
marlowe-runtime/gen/Language/Marlowe/Runtime/Transaction/Gen.hs
marlowe-runtime/marlowe-runtime.cabal
marlowe-runtime/test/Language/Marlowe/Runtime/Transaction/ApiSpec.hs
marlowe-runtime/tx-api/Language/Marlowe/Runtime/Transaction/Api.hs
marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/BuildConstraints.hs

- Branch
- PR
[PLT-3953]: https://input-output.atlassian.net/browse/PLT-3953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PLT-3953: Support --roles-config-file in Marlowe Runtime CLI

---

RELEASE.md

For the first release: no changelog exists yet, we should just do more thorough smoke testing.

PLT-4221 Add draft release process document

---

marlowe/src/Language/Marlowe/Core/V1/Semantics.hs

Added missing comment, per audit report.
- Branch
- PR

PLT-3382 Elaborate comment on `refundOne`.

---

.github/workflows/test.yml
cardano-integration/src/Test/Integration/Cardano/Local.hs
marlowe-integration/marlowe-integration.cabal
marlowe-integration/src/Test/Integration/Marlowe/Local.hs

Running some experiments to investigate and improve integration test stability.

Test stability

---

nix/dev/compose.nix

I bumped the version of the packages so after a clean `cabal build` we point to the correct local executables.
- Branch
- PR

PLT-5529 - Fix package version numbers in the docker compose derivation

---

.github/workflows/test.yml
marlowe-integration-tests/marlowe-integration-tests.cabal
marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/ApplyInputs.hs
marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/Common.hs
marlowe-integration-tests/test/Language/Marlowe/Runtime/IntegrationSpec.hs

Just adds tests for apply inputs. Opted for manual scenarios over generated ones, as the number of combinations was too huge. Review: Can you think of any really important edge cases I'm missing here?
- Branch
- PR

PLT-5270 Apply Inputs Integration Tests

---

marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/REST/ApiError.hs

Improve REST error codes

---

marlowe-protocols/src/Network/Protocol/Peer/Trace.hs
marlowe-runtime/changelog.d/20230515_101947_jhbertra_fix_driver_bug.md

Fix threading of driver state

---

marlowe-apps/ReadMe.md
marlowe-apps/Signing.md
marlowe-apps/changelog.d/20230524_064345_brian.bush_hackathon.rst
marlowe-apps/marlowe-apps.cabal
marlowe-apps/signing/Main.hs

A simple service to sign transactions in demonstrations.
- Branch
- PR

Signing service developed during Marlowe hackathon.

---

marlowe-runtime/doc/ReadMe.md

Propose removing the section about AWS Lambda Interface.

Update ReadMe.md to remove Lambda section

---

marlowe-runtime/doc/ReadMe.md
marlowe/best-practices.md
marlowe/example-contracts.md
marlowe/test/ReadMe.md

Renamed `marlowe-finance.io` to `marlowe.iohk.io`.
- Branch
- PR

Updated links to point to new Marlowe website and Playground.

---

deploy/nomadTasks.nix
deploy/operables.nix
nix/dev/compose.nix

PLT-6117 Fixed erroneous option for `marlowe-proxy` in operables.

---

marlowe-runtime/changelog.d/20230602_132507_brian.bush_PLT_5901.md
marlowe-runtime/test/Language/Marlowe/Runtime/Transaction/SafetySpec.hs
marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Safety.hs
marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Server.hs
marlowe-test/changelog.d/20230602_132224_brian.bush_PLT_5901.rst
marlowe-test/src/Spec/Marlowe/Semantics/Arbitrary.hs
marlowe/changelog.d/20230602_132119_brian.bush_PLT_5901.md
marlowe/src/Language/Marlowe/Analysis/Safety/Ledger.hs
marlowe/src/Language/Marlowe/Analysis/Safety/Types.hs
marlowe/src/Language/Marlowe/Core/V1/Plate.hs
marlowe/src/Language/Marlowe/Scripts.hs

This checks a contract and its initial state for . . .
1. That it does not mix mainnet and testnet addresses.
2. That its address survive round-trip serialization.
- Branch
- PR

PLT-5901 Implemented checks for valid network addresses.

---

marlowe-runtime-cli/app/Language/Marlowe/Runtime/CLI/Command/Apply.hs
marlowe-runtime/changelog.d/20230602_164218_jhbertra_plt_5623_choose_description.md

PLT-5623 Description for "choose" option in marlowe-runtime-cli is wrong

---

marlowe-apps/src/Language/Marlowe/Runtime/App/Build.hs
marlowe-cli/cli-test/Language/Marlowe/CLI/Test/Runtime/Interpret.hs
marlowe-client/src/Control/Monad/Trans/Marlowe/Class.hs
marlowe-integration-tests/marlowe-integration-tests.cabal
marlowe-integration-tests/test/Language/Marlowe/Runtime/CliSpec.hs
marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/Basic.hs
marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/Common.hs
marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/MarloweQuery.hs
marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/StandardContract.hs
marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/Withdraw.hs
marlowe-integration-tests/test/Language/Marlowe/Runtime/IntegrationSpec.hs
marlowe-runtime-cli/app/Language/Marlowe/Runtime/CLI/Command/Withdraw.hs
marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/TxClient.hs
marlowe-runtime/gen/Language/Marlowe/Runtime/Transaction/Gen.hs
marlowe-runtime/test/Language/Marlowe/Runtime/Transaction/CommandSpec.hs
marlowe-runtime/tx-api/Language/Marlowe/Runtime/Transaction/Api.hs
marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Server.hs

PLT-5271 Withdraw Tests

---

marlowe-runtime/doc/resources.md

Re-ran benchmarks for public networks (syncing, scaling, finding) and revised recommendations for resources for Marlowe Runtime components.
- Branch
- PR

PLT-6141 Revised resource recommendations.

---

marlowe-runtime-web/changelog.d/20230621_120958_nicolas.henin_payout.md
marlowe-runtime-web/marlowe-runtime-web.cabal
marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/DTO.hs
marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/Types.hs
marlowe-runtime-web/test/Spec.hs

- **JIRA** : [PLT-6203](https://input-output.atlassian.net/browse/PLT-6203?atlOrigin=eyJpIjoiZjRjOTE4ZmQzMDE2NDQyM2FhYTMxNzA1MzdkYjUxNTMiLCJwIjoiaiJ9)
- **Runtime REST** 
- **Value** : Add Unclaimed Payouts in the endpoint `Get /Contract/:contractId/` 
- Addition in Payload : `Get /Contract/:contractId/`
```json
{
"links": {
"transactions": "string"
},
"resource": {
"block": {
"blockHeaderHash": "string",
"blockNo": 0,
"slotNo": 0
},
"continuations": "string",
"contractId": "98d601c9307dd43307cf68a03aad0086d4e07a789b66919ccf9f7f7676577eb7#1",
"metadata": {},
"roleTokenMintingPolicyId": "string",
"state": {
"accounts": [
[
null
]
],
"boundValues": [
[
null
]
],
"choices": [
[
null
]
],
"minTime": 0
},
"status": "unsigned",
"tags": {},
"txBody": {
"cborHex": "string",
"description": …
```

PLT-6203 : Add Unclaimed Payouts in ContractState Payload

---

flake.lock
flake.nix
nix/haskell-project.nix
nix/hydra-jobs.nix
nix/iogx-config.nix
nix/per-system-outputs.nix
nix/pre-commit-check.nix
nix/shell.nix

Bump IOGX to [bc5f588a5c706555a73431d6871bc3858d651cf6](https://www.github.com/input-output-hk/iogx/commit/bc5f588a5c706555a73431d6871bc3858d651cf6)

Bump IOGX to bc5f588

---

marlowe-runtime/test/Language/Marlowe/Runtime/Transaction/SafetySpec.hs

Tested detection of contracts that fail to validator due to Plutus execution cost overrun.
- Branch
- PR

PLT-6362 Added safety test for contract with prohibitive execution cost.

---

flake.lock
marlowe-cli/src/Language/Marlowe/CLI/Orphans.hs
marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/Next/Schema.hs
marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/Orphans.hs
marlowe-runtime/plutus-scripts/Language/Marlowe/Runtime/Plutus/V2/Scripts/MarloweV1/RoleTokensPolicy.hs
marlowe-runtime/plutus-scripts/Language/Marlowe/Runtime/Plutus/V2/Scripts/MarloweV1/RoleTokensPolicy/Types.hs
marlowe-test/src/Spec/Marlowe/Plutus/Arbitrary.hs
marlowe-test/src/Spec/Marlowe/Semantics/Next/Arbitrary.hs
marlowe-test/src/Spec/Marlowe/Semantics/Next/Common/Isomorphism.hs
marlowe-test/src/Spec/Marlowe/Semantics/Orphans.hs
marlowe/src/Language/Marlowe/Core/V1/Semantics.hs
marlowe/src/Language/Marlowe/Core/V1/Semantics/Types.hs
marlowe/src/Language/Marlowe/Scripts.hs
nix/iogx-config.nix

Bump IOGX to [04ef47](https://www.github.com/input-output-hk/iogx/commit/04ef47859c11ac06d459d095b59304e890327a8f)

Bump IOGX to 04ef47

---

marlowe-chain-sync/marlowe-chain-sync.cabal
marlowe-client/marlowe-client.cabal
marlowe-runtime-cli/marlowe-runtime-cli.cabal
marlowe-runtime-web/marlowe-runtime-web.cabal
marlowe-runtime/changelog.d/20230711_083919_jhbertra_plt_6569_tag_schema_fix.md
marlowe-runtime/marlowe-indexer/deploy/tag-text.sql
marlowe-runtime/marlowe-indexer/revert/tag-text.sql
marlowe-runtime/marlowe-indexer/sqitch.plan
marlowe-runtime/marlowe-indexer/verify/tag-text.sql
marlowe-runtime/marlowe-runtime.cabal
nix/marlowe-cardano/compose.nix

This is a hotfix brnach from 0.0.2. Merging will be performed manually to integrate changes with `main`

DO NOT MERGE Jhbertra/runtime 0.0.3

---

marlowe-chain-sync/deploy/new-partitions.sql
marlowe-chain-sync/revert/new-partitions.sql
marlowe-chain-sync/sqitch.plan
marlowe-chain-sync/verify/new-partitions.sql
marlowe-runtime/changelog.d/20230728_105313_jhbertra_plt_6650_increase_slot_limit.md

Added new migration to increase slot limit to 200,000,000
- Branch
- PR

Add new partitions for up to slot 200m in migration

---

marlowe-runtime-web/marlowe-runtime-web.cabal
marlowe-runtime-web/test/Spec.hs

- Had to do some type-level surgery on the API type to make the test suite machinery work.
- Branch
- PR

SCP-6906 Web Tests not Running

---

marlowe-object/changelog.d/20230803_101546_jhbertra_bundler.md
marlowe-object/gen/Language/Marlowe/Object/Gen.hs
marlowe-object/marlowe-object.cabal
marlowe-object/src/Language/Marlowe/Object/Bundler.hs
marlowe-object/test/Language/Marlowe/Object/BundlerSpec.hs
marlowe-object/test/Language/Marlowe/Object/TypesSpec.hs

Monadic Contract Bundler

---

marlowe-runtime/changelog.d/20230803_152356_jhbertra_scp_6848_submission_hangs.md
marlowe-runtime/marlowe-runtime.cabal
marlowe-runtime/runtime/Language/Marlowe/Runtime.hs
marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Server.hs
marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Submit.hs

SCP-6848 Tx submission hangs

---

marlowe-cli/changelog.d/20230808_125218_brian.bush_PLT_6907.md
marlowe-cli/marlowe-cli.cabal
marlowe-cli/src/Language/Marlowe/CLI/Analyze.hs
marlowe-cli/src/Language/Marlowe/CLI/Merkle.hs
marlowe-cli/tests/Spec.hs
marlowe-cli/tests/Spec/Analysis.hs
marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/REST/ContractSources.hs
marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Safety.hs
marlowe-test/src/Spec/Marlowe/Plutus/Script.hs
marlowe/changelog.d/20230808_125311_brian.bush_PLT_6907.md
marlowe/src/Language/Marlowe/Analysis/Safety/Transaction.hs
marlowe/src/Language/Marlowe/Core/V1/Merkle.hs
nix/haskell-project.nix

Fixed deep demerkleization of contract for the Plutus execution-cost analysis, and added golden tests for that.
- Branch
- PR

PLT-6907 Fixed execution cost analysis of merkleized contracts

---

README.adoc

- Branch
- (N/A) Tests are provided (if possible)
- (N/A) [Test report is updated](https://github.com/input-output-hk/marlowe-cardano/blob/main/marlowe/test/test-report.md) (if relevant)
- PR

Remove outdated deployment info from README.md

---

marlowe-cli/cli-test/Language/Marlowe/CLI/Test/Runtime/Interpret.hs
marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/ApplyInputs.hs
marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/Basic.hs
marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/Common.hs
marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/MarloweQuery.hs
marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/Contracts/Contract/Get.hs
marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/Contracts/Transactions/Transaction/Get.hs
marlowe-runtime-web/changelog.d/20230816_074618_jhbertra_plt_5376_payments_in_tx.md
marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/DTO.hs
marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/Types.hs
marlowe-runtime-web/test/Spec.hs
marlowe-runtime/gen/Language/Marlowe/Runtime/Transaction/Gen.hs
marlowe-runtime/marlowe-runtime.cabal
marlowe-runtime/test/Language/Marlowe/Runtime/Core/MetadataSpec.hs
marlowe-runtime/test/Language/Marlowe/Runtime/Transaction/ApiSpec.hs
marlowe-runtime/test/Language/Marlowe/Runtime/Transaction/CommandSpec.hs
marlowe-runtime/tx-api/Language/Marlowe/Runtime/Transaction/Api.hs
marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Server.hs

PLT-5376 add assets to payouts, contract state, and transactions

---

marlowe-runtime-web/CHANGELOG.md
marlowe-runtime-web/marlowe-runtime-web.cabal
marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/OpenAPI.hs
marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/REST/Contracts.hs
marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/API.hs
marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/Client.hs
marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/Types.hs

- Populated info with title, description, version, license
- Added security key to all paths
- Fixed invalid component names
- Added servers object for staging servers and localhost
- Added summaries, descriptions, and operationIDs to endpoints.
- Branch
- PR

PLT-5458 Open API Improvements

---

marlowe-cli/command/Language/Marlowe/CLI/Command/Run.hs
marlowe-cli/src/Language/Marlowe/CLI/Types.hs

PLT-7663 Fix `marlowe cli run`

---

marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/Basic.hs
marlowe-runtime/changelog.d/20230928_121137_jhbertra_plt_6904_ada_role_token.md
marlowe-runtime/test/Language/Marlowe/Runtime/Transaction/ConstraintsSpec.hs
marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Constraints.hs

PLT-6904 Marlowe Runtime fails to create transaction involving ada as the role token

---

marlowe-protocols/changelog.d/20231011_150503_jhbertra_plt_3513_improve_failures.md
marlowe-protocols/src/Network/Channel.hs
marlowe-protocols/src/Network/Channel/Typed.hs
marlowe-protocols/src/Network/Protocol/ChainSeek/Types.hs
marlowe-protocols/src/Network/Protocol/Codec.hs
marlowe-protocols/src/Network/Protocol/Codec/Spec.hs
marlowe-protocols/src/Network/Protocol/Driver.hs
marlowe-protocols/src/Network/Protocol/Driver/Trace.hs
marlowe-protocols/src/Network/Protocol/Handshake/Types.hs
marlowe-protocols/src/Network/Protocol/Job/Types.hs
marlowe-protocols/src/Network/Protocol/Query/Types.hs
marlowe-runtime-web/app/Main.hs
marlowe-runtime-web/marlowe-runtime-web.cabal
marlowe-runtime/contract-api/Language/Marlowe/Protocol/Load/Types.hs
marlowe-runtime/contract-api/Language/Marlowe/Protocol/Transfer/Types.hs
marlowe-runtime/contract/Data/Marlowe/LiveContracts.hs
marlowe-runtime/discovery-api/Language/Marlowe/Protocol/HeaderSync/Types.hs
marlowe-runtime/history-api/Language/Marlowe/Protocol/Sync/Types.hs
marlowe-runtime/proxy-api/Language/Marlowe/Protocol/Types.hs
marlowe-runtime/sync-api/Language/Marlowe/Protocol/BulkSync/Types.hs
nix/marlowe-cardano/compose.nix
nix/marlowe-cardano/deploy/operables.nix
scripts/local-docker.env

PLT-3515 Close communication gracefully

---

marlowe-protocols/changelog.d/20231011_150503_jhbertra_plt_3513_improve_failures.md
marlowe-protocols/src/Network/Channel.hs
marlowe-protocols/src/Network/Channel/Typed.hs
marlowe-protocols/src/Network/Protocol/ChainSeek/Types.hs
marlowe-protocols/src/Network/Protocol/Codec.hs
marlowe-protocols/src/Network/Protocol/Codec/Spec.hs
marlowe-protocols/src/Network/Protocol/Driver.hs
marlowe-protocols/src/Network/Protocol/Driver/Trace.hs
marlowe-protocols/src/Network/Protocol/Handshake/Types.hs
marlowe-protocols/src/Network/Protocol/Job/Types.hs
marlowe-protocols/src/Network/Protocol/Query/Types.hs
marlowe-runtime-web/app/Main.hs
marlowe-runtime-web/marlowe-runtime-web.cabal
marlowe-runtime/contract-api/Language/Marlowe/Protocol/Load/Types.hs
marlowe-runtime/contract-api/Language/Marlowe/Protocol/Transfer/Types.hs
marlowe-runtime/contract/Data/Marlowe/LiveContracts.hs
marlowe-runtime/discovery-api/Language/Marlowe/Protocol/HeaderSync/Types.hs
marlowe-runtime/history-api/Language/Marlowe/Protocol/Sync/Types.hs
marlowe-runtime/proxy-api/Language/Marlowe/Protocol/Types.hs
marlowe-runtime/sync-api/Language/Marlowe/Protocol/BulkSync/Types.hs

Reverting #727 because the change caused difficult to diagnose bugs. Will attempt another implementation but this should fix some issues currently affecting QA for now.

PLT-8044 message frames

---

marlowe-chain-sync/marlowe-chain-indexer/Options.hs
marlowe-chain-sync/marlowe-chain-sync.cabal
marlowe-chain-sync/marlowe-chain-sync/Options.hs
marlowe-runtime/changelog.d/20231020_085010_jhbertra_plt_3312_help_text.md
marlowe-runtime/marlowe-contract/Main.hs
marlowe-runtime/marlowe-indexer/Main.hs
marlowe-runtime/marlowe-proxy/Main.hs
marlowe-runtime/marlowe-runtime.cabal
marlowe-runtime/marlowe-sync/Main.hs
marlowe-runtime/marlowe-tx/Main.hs

PLT-3312 More help text

---

marlowe-cli/src/Language/Marlowe/CLI/Analyze.hs
marlowe-cli/tests/Spec/Analysis.hs
marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/Orphans.hs
marlowe-runtime/changelog.d/20231102_170110_brian.bush_PLT_7683.md
marlowe-runtime/src/Language/Marlowe/Runtime/Core/Api.hs
marlowe-runtime/test/Language/Marlowe/Runtime/Transaction/SafetySpec.hs
marlowe-runtime/tx-api/Language/Marlowe/Runtime/Transaction/Api.hs
marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/BuildConstraints.hs
marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Query/Helper.hs
marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Safety.hs
marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Server.hs
marlowe-test/src/Spec/Marlowe/Semantics/Arbitrary.hs
marlowe/src/Language/Marlowe/Analysis/Safety/Transaction.hs
marlowe/src/Language/Marlowe/Analysis/Safety/Types.hs

The safety check for open roles mocks up the `HelperContext` so that the mock execution accounts for situations where the open-role validator runs alongside the Marlowe validator.
- Branch
- PR

PLT-7683 Safety checks for open roles

---

marlowe-runtime-web/.golden/OpenApi/golden
marlowe-runtime-web/changelog.d/20231108_141923_jhbertra_plt_4236_open_api_improvements.md
marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/API.hs
marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/Types.hs

PLT-4236 Various Open API improvements

---

deploy/marlowe-runtime/templates/chain-indexer.yaml
deploy/marlowe-runtime/templates/chain-sync.yaml
deploy/marlowe-runtime/templates/marlowe-contract.yaml
deploy/marlowe-runtime/templates/marlowe-indexer.yaml
deploy/marlowe-runtime/templates/marlowe-proxy.yaml
deploy/marlowe-runtime/templates/marlowe-sync.yaml
deploy/marlowe-runtime/templates/marlowe-tx.yaml
deploy/marlowe-runtime/templates/marlowe-web-server.yaml
deploy/marlowe-runtime/values.yaml

PR to abstract OTEL exporter endpoint into the values.yaml file for reusability.

Abstract OTEL exporter endpoint

---

.github/workflows/test.yml
marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/MarloweQuery.hs
marlowe-runtime/changelog.d/20231120_130123_jhbertra_plt_8029_index_marlowe_accounts.md
marlowe-runtime/indexer/Language/Marlowe/Runtime/Indexer/Database/PostgreSQL/CommitBlocks.hs
marlowe-runtime/indexer/Language/Marlowe/Runtime/Indexer/Party.hs
marlowe-runtime/marlowe-indexer/deploy/resetParties.sql
marlowe-runtime/marlowe-indexer/revert/resetParties.sql
marlowe-runtime/marlowe-indexer/sqitch.plan
marlowe-runtime/marlowe-indexer/verify/resetParties.sql
marlowe-runtime/marlowe-runtime.cabal

PLT-8029 index parties in state accounts

---

marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/Types.hs

Add hint for url-encoding the # in contract IDs

---

marlowe-test/test/Spec/Marlowe/Semantics/Next.hs
marlowe-test/test/Spec/Marlowe/Semantics/Next/Contract/When/Deposit.hs
marlowe/changelog.d/20231205_151514_jhbertra_plt_8886_next_parties_reversed.md
marlowe/src/Language/Marlowe/Core/V1/Next/Applicables/CanDeposit.hs

PLT-8886 Swap the order of account and party in CanDeposit

---

.github/workflows/deploy.yml

Allow auto-commit for CD to bypass branch protections

---

marlowe-test/chain/compare.sql
marlowe-test/changelog.d/20231212_134340_brian.bush_PLT_5290.md

Revised Marlowe vs DB Sync database-comparsion scripts to conform to recent changes in Marlowe `chain` schema.
- Branch
- PR

PLT-5290 Revised db-comparison scripts to conform to new `chain` schema.

---

marlowe-runtime/doc/open-roles.md

Updated open-role documentation to reflect recent REST API changes.
- Branch
- PR

PLT-8703 Update documentation for open roles.

---

marlowe-runtime/doc/resources.md

Measured Runtime's resource footprint on three public networks and updated guidance in documentation.
- Branch
- PR

PLT-3623 Re-measured Runtime resource requirements.

---

marlowe-runtime/doc/resources.md

Measured Runtime's resource footprint on three public networks and updated guidance in documentation.
- Branch
- PR

PLT-3623 Updated `marlowe-contract` resource measurements for testnets.

---

.github/workflows/deploy.yml
deploy/marlowe-oracle/Chart.yaml
deploy/marlowe-oracle/templates/marlowe-oracle.yaml
deploy/marlowe-oracle/values.yaml

PLT-9003: Add marlowe-oracle deployment

---

marlowe-benchmark/ReadMe.md
marlowe-benchmark/app/Language/Marlowe/Runtime/Benchmark.hs
marlowe-benchmark/app/Language/Marlowe/Runtime/Benchmark/BulkSync.hs
marlowe-benchmark/app/Language/Marlowe/Runtime/Benchmark/HeaderSync.hs
marlowe-benchmark/app/Language/Marlowe/Runtime/Benchmark/Lifecycle.hs
marlowe-benchmark/app/Language/Marlowe/Runtime/Benchmark/Lifecycle/Contracts.hs
marlowe-benchmark/app/Language/Marlowe/Runtime/Benchmark/Lifecycle/Scenario.hs
marlowe-benchmark/app/Language/Marlowe/Runtime/Benchmark/Query.hs
marlowe-benchmark/app/Language/Marlowe/Runtime/Benchmark/Sync.hs
marlowe-benchmark/app/Main.hs
marlowe-benchmark/changelog.d/20240105_092608_brian.bush_PLT_9013.rst
marlowe-benchmark/marlowe-benchmark.cabal

Implemented benchmark for basic contract lifecycle. See updated documentation in https://github.com/input-output-hk/marlowe-cardano/tree/PLT-9013/marlowe-benchmark#readme.
- Branch
- PR

PLT-9013 Implemented benchmark for basic contract lifecycle.

---

marlowe-runtime-web/.golden/OpenApi/golden
marlowe-runtime-web/changelog.d/20240111_114659_jhbertra_plt_9083_initial_state_in_response.md
marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/DTO.hs
marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/Types.hs
marlowe-runtime-web/test/Spec.hs

PLT-9083 initial state in response

---

marlowe-cli/flake.lock
marlowe-runtime/doc/deployment.md
marlowe-runtime/doc/tutorial.md
marlowe/README.md
nix/marlowe-cardano/deploy/README.md

Some `nix run` commands in various doc files were obsolete. This PR addresses this.

Fix broken commands in various doc files

---

marlowe-runtime/src/Language/Marlowe/Runtime/Core/ScriptRegistry.hs

Published reference scripts permanently on `mainnet`.
```bash
marlowe-cli transaction publish \
--mainnet \
--permanently stake1u9c07x9z7w35zmm5tumm5lpltdjpma8gx95y9vw7e35j67gz7r8a7 \
. . .
```
```console
Fee: Lovelace 780357
Size: 13854 / 16384 = 84%
Execution units:
Memory: 0 / 14000000 = 0%
Steps: 0 / 10000000000 = 0%
Fee: Lovelace 351797
Size: 4114 / 16384 = 25%
Execution units:
Memory: 0 / 14000000 = 0%
Steps: 0 / 10000000000 = 0%
Marlowe script published at address: addr1q8cmu4u3quhxgansnxvfuzn5a9u6khvff4kggy35f5xl2qtsluv29uarg9hhghehhf7r7kmyrh6wsvtgg2caanrf94uscc58wh
Marlowe script hash: "377325ad84a55ba0282d844dff2d5f0f18c33fd4a28a0a9d73c6f60d"
Marlowe ref script UTxO min ADA: Lovelace 48776270
Marlowe ref script UTxO: TxIn …
```

PLT-9304 Published reference scripts permanently on `mainnet`.

---

marlowe-runtime/changelog.d/20240118_112759_jhbertra_plt_9294_marlowe_indexer_crash_when_syncing_from_genesis.md
marlowe-runtime/indexer/Language/Marlowe/Runtime/Indexer/ChainSeekClient.hs

Plt 9294 marlowe indexer crash when syncing from genesis

---

marlowe-runtime/changelog.d/20240118_140815_jhbertra_marlowe_contract_memory.md
marlowe-runtime/contract/Data/Marlowe/LiveContracts.hs
marlowe-runtime/contract/Language/Marlowe/Runtime/Contract/GarbageCollector.hs
marlowe-runtime/test/Data/Marlowe/LiveContractsSpec.hs

Fix marlowe-contract memory problems

---

marlowe-cli/cli-test/Language/Marlowe/CLI/Test/Wallet/Interpret.hs
marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/ApplyInputs.hs
marlowe-runtime-web/changelog.d/20231228_102217_tomasz.rybarczyk_PLT_9050_improve_error_reporting.md
marlowe-runtime-web/marlowe-runtime-web.cabal
marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/DTO.hs
marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/REST/ApiError.hs
marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/Types.hs
marlowe-runtime/gen/Language/Marlowe/Runtime/Transaction/Gen.hs
marlowe-runtime/test/Language/Marlowe/Runtime/Transaction/BuildConstraintsSpec.hs
marlowe-runtime/test/Language/Marlowe/Runtime/Transaction/ConstraintsSpec.hs
marlowe-runtime/tx-api/Language/Marlowe/Runtime/Transaction/Api.hs
marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/BuildConstraints.hs
marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Constraints.hs

* Add more structured information to some of the reports
* Encode every error structure explicite - drop generic helper which leaked internal implementation details.
- Branch
- PR

Improve error reporting on the REST level (PLT-9050)

---

.github/workflows/nightly.yml

Enabled nightly test using `marlowe-benchmark`.
- Branch
- PR

PLT-9208 Enabled nightly tests.

---

.github/workflows/deploy.yml
.github/workflows/nightly.yml
.github/workflows/test.yml
marlowe-benchmark/app/Language/Marlowe/Runtime/Benchmark.hs
nix/marlowe-cardano/deploy/operables.nix

1. Updated operable.
2. Made default lifecycle test most stressful.
- Branch
- PR

PLT-9208 Adjusted benchmarking defaults.

---

marlowe-chain-sync/chain-indexer/Language/Marlowe/Runtime/ChainIndexer/Database/PostgreSQL.hs
marlowe-chain-sync/libchainsync/Language/Marlowe/Runtime/ChainSync/Database/PostgreSQL.hs
marlowe-chain-sync/marlowe-chain-indexer/Main.hs
marlowe-integration/src/Test/Integration/Marlowe/Local.hs
marlowe-runtime/changelog.d/20240205_073643_jhbertra_dup_blocks.md
marlowe-runtime/marlowe-runtime/Main.hs

Handle duplicate block rows

---

.github/workflows/deploy.yml

Fix deploy workflow by explicitely declaring permissions set.

fix: deploy workflow

---

marlowe-test/marlowe-test.cabal
marlowe-test/test/Spec.hs
marlowe-test/test/Spec/Marlowe/Plate.hs
marlowe/src/Language/Marlowe/Core/V1/Plate.hs

Fix parties plate - extract party from `Account` payee.

---

.github/workflows/nightly.yml

This attempts to fix the nightly builds

Update marlowe-benchmark command in nightly.yml
