- marlowe-actus/test/Spec/Marlowe/ACTUS/Examples.hs
- marlowe/cli/Main.hs
- marlowe/src/Language/Marlowe.hs
- marlowe/src/Language/Marlowe/Analysis/FSSemantics.hs
- marlowe/src/Language/Marlowe/Client.hs
- marlowe/src/Language/Marlowe/Deserialisation.hs
- marlowe/src/Language/Marlowe/Scripts.hs
- marlowe/src/Language/Marlowe/Semantics.hs
- marlowe/src/Language/Marlowe/SemanticsDeserialisation.hs
- marlowe/src/Language/Marlowe/SemanticsSerialisation.hs
- marlowe/src/Language/Marlowe/SemanticsTypes.hs
- marlowe/src/Language/Marlowe/Serialisation.hs
- marlowe/src/Language/Marlowe/Util.hs
- marlowe/test/Spec/Marlowe/Common.hs
- marlowe/test/Spec/Marlowe/Marlowe.hs
This PR adds merkleization to the Plutus semantics and updates:
- JSON serialisation and deserialisation (in a way that is backwards compatible)
- Haskell code that depends on the format of inputs
And also:
- Adds a test for merkleized excution
- Augment QuickCheck generator to include MerkleizedCase
I had to revert the deserialisation implementation to the tree version because Plutus doesn't implement matching on integers.
- Branch
- PR
> SCP-643 - Implement merkleization in Plutus semantics

- marlowe-dashboard-client/README.md
- marlowe-dashboard-client/default.nix
- marlowe-dashboard-client/docs/use-cases/Readme.md
- marlowe-dashboard-client/docs/use-cases/wallet.md
- marlowe-dashboard-client/entry.js
- marlowe-dashboard-client/spago-packages.nix
- marlowe-dashboard-client/src/API/Marlowe/Run/TestnetWallet.purs
- marlowe-dashboard-client/src/Capability/Marlowe.purs
- marlowe-dashboard-client/src/Capability/PlutusApps/MarloweApp/Types.purs
- marlowe-dashboard-client/src/Main.purs
- marlowe-dashboard-client/src/MainFrame/State.purs
- marlowe-dashboard-client/src/Page/Welcome/Lenses.purs
- marlowe-dashboard-client/src/Page/Welcome/State.purs
- marlowe-dashboard-client/src/Page/Welcome/Types.purs
- marlowe-dashboard-client/src/Page/Welcome/View.purs
- marlowe-dashboard-client/webpack.config.js
- marlowe-dashboard-server/src/Marlowe/Run/Webserver/Server.hs
- packages.dhall
This PR adds a modal to restore a wallet from the centralized server using the endpoint created in [PR 27](https://github.com/input-output-hk/marlowe-cardano/pull/27). We can now advance to the Main screen but we can't create a contract yet.
- Branch
- PR
> SCP-3089 - Marlowe Run Frontend - Re implement welcome page with wallet restore

- marlowe-playground-client/src/Component/Blockly/State.purs
- marlowe-playground-client/src/Marlowe/Blockly.purs
- marlowe-playground-client/src/Marlowe/Gen.purs
- marlowe-playground-client/src/Marlowe/Holes.purs
- marlowe-playground-client/src/Marlowe/Linter.purs
The `Proxy a` in `Hole a` carries no information as `a` type is already in the `Hole` type itself. I've simplified the implementation and provided the `Proxy a` in a place where it is required based on the `a` parameter from the `Hole a` type.
This work was done alongside SCP-3164 which works with `Marlowe.Holes`.
> Drop unnecessary Proxy from Marlowe.Hole constructor

- marlowe-dashboard-client/src/API/Marlowe/Run/Wallet.purs
- marlowe-dashboard-client/src/API/Marlowe/Run/Wallet/CentralizedTestnet.purs
- marlowe-dashboard-client/src/API/Url.purs
- marlowe-dashboard-client/src/Capability/Marlowe.purs
- marlowe-dashboard-client/src/Capability/Wallet.purs
- marlowe-dashboard-client/src/Component/Contacts/Types.purs
- marlowe-dashboard-client/src/Page/Welcome/State.purs
- marlowe-dashboard-server/app/PSGenerator.hs
- marlowe-dashboard-server/marlowe-dashboard-server.cabal
- marlowe-dashboard-server/src/Marlowe/Run/Webserver/API.hs
- marlowe-dashboard-server/src/Marlowe/Run/Webserver/Server.hs
- marlowe-dashboard-server/src/Marlowe/Run/Webserver/Types.hs
- marlowe-dashboard-server/src/Marlowe/Run/Webserver/Wallet/API.hs
- marlowe-dashboard-server/src/Marlowe/Run/Webserver/Wallet/CentralizedTestnet/API.hs
- marlowe-dashboard-server/src/Marlowe/Run/Webserver/Wallet/CentralizedTestnet/Server.hs
- marlowe-dashboard-server/src/Marlowe/Run/Webserver/Wallet/CentralizedTestnet/Types.hs
- marlowe-dashboard-server/src/Marlowe/Run/Webserver/Wallet/Client.hs
- marlowe-dashboard-server/src/Marlowe/Run/Webserver/Wallet/Server.hs
- marlowe-dashboard-server/src/Marlowe/Run/Webserver/Wallet/Types.hs
- nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-dashboard-server.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-dashboard-server.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/marlowe-dashboard-server.nix
This PR refactors the current backend to modularize endpoints.
It also adds a new endpoint for get the total funds from the WBE.
Note that the `restoreWallet` is placed under a `CentralizedTestnet` module, indicating that this endpoint is only useful in that architecture, but the getTotalFunds is placed in plain Wallet, as its going to be useful for this architecture and also the full node one.
The previous `restoreWallet` endpoint is now under
```
POST /api/wallet/centralized-testnet/restore
{  "getMnemonicPhrase" : ["word1", "word2", "...", "word24"]
,  "getPassphrase": "something"
, "getWalletName": "my-wallet"
}
```
The new `getTotalFunds is under
```
GET /api/wallet/<wallet-id>/get-total-funds
```
- Branch
- PR
> SCP-3132 Get total funds through WBE (part 1 - backend API)

- flake.lock
- flake.nix
- marlowe-dashboard-client/default.nix
- marlowe-playground-client/README.md
- marlowe-playground-client/default.nix
- marlowe-playground-client/entry.js
- marlowe-playground-client/package-lock.json
- marlowe-playground-client/package.json
- marlowe-playground-client/spago-packages.nix
- marlowe-playground-client/webpack.config.js
- marlowe-playground-client/webpack.vendor.config.js
- packages.dhall
- shell.nix
It seems that it should not affect production builds in any way but please read it through with me.
For testing it is required to use a branch of [`web-common`](https://github.com/paluh/purescript-web-common/tree/optimize-webpack-rebuilds) and point to it in the build terminal (before running `npm`) by (please use absolute path!):
`export WEB_COMMON_SRC=/home/paluh/programming/purescript/projects/web-common`
Commit message:
* Drop `purs-loader`. We just assume here that the compilation itself is done
by programmer "ide" (possibly editor + `purescript-lts` / `purs ide server` or `pscid`).
* Add "dll" prebundling step by introducing `DllPlugin` into the dev
build. I've decided to use separate `webpack.vendor.config.js` for
additional prebundling step.
* Drop `CommonChunksPlugin` …
> SCP-3165 optimize development workflow with webpack

- marlowe-dashboard-client/src/Capability/Marlowe.purs
- marlowe-dashboard-client/src/Capability/MarloweStorage.purs
- marlowe-dashboard-client/src/Capability/Wallet.purs
- marlowe-dashboard-client/src/Component/Contacts/State.purs
- marlowe-dashboard-client/src/Component/Contacts/Types.purs
- marlowe-dashboard-client/src/MainFrame/State.purs
- marlowe-dashboard-client/src/Page/Dashboard/Lenses.purs
- marlowe-dashboard-client/src/Page/Dashboard/State.purs
- marlowe-dashboard-client/src/Page/Dashboard/Types.purs
- marlowe-dashboard-client/src/Page/Welcome/State.purs
This is part 2 of [this PR](https://github.com/input-output-hk/marlowe-cardano/pull/37). It gets both the ada value and the custom tokens (including role tokens) from the WalletBackEnd.
There is an important warning under the `Note [polling updateTotalFunds]` which may cause some bugs while the wallet is syncing. I created two issues to solve that SCP-3211 (add global polling to getTotalFunds) and SCP-3212 (Show wallet sync status in the UI) 
- Branch
- PR
> SCP-3195 - Re implement get total funds through WBE (part 2 frontend)

- marlowe-dashboard-client/src/Capability/Marlowe.purs
- marlowe-dashboard-client/src/Capability/PAB.purs
- marlowe-dashboard-client/src/Capability/PlutusApps/MarloweApp.purs
- marlowe-dashboard-client/src/Control/Concurrent/EventBus.purs
- marlowe-dashboard-client/src/Data/Slot.purs
- marlowe-dashboard-client/src/Env.purs
- marlowe-dashboard-client/src/Main.purs
- marlowe-dashboard-client/src/MainFrame/State.purs
- marlowe-dashboard-client/src/Page/Dashboard/State.purs
- marlowe-dashboard-client/src/Page/Dashboard/Types.purs
- marlowe-dashboard-client/src/Store.purs
- marlowe-dashboard-client/test/Data/Plutus.purs
- marlowe-dashboard-client/test/Main.purs
- marlowe-dashboard-client/test/Marlowe/Run.purs
- marlowe-dashboard-client/test/Marlowe/Run/Commands.purs
- marlowe-dashboard-client/test/Marlowe/Run/Flows.purs
- marlowe-dashboard-client/test/Marlowe/Run/Scenarios/Contract.purs
- marlowe-dashboard-client/test/Marlowe/Run/Scenarios/Wallet.purs
- marlowe-dashboard-client/test/Network/HTTP.purs
Changes:
- Kill and restart MarloweApp after 3 ~minute~ block timeout (blocks are counted by the number of `SlotChange` messages we get from the PAB, ignoring any smaller slots than previously seen, e.g. when the PAB hits a rollback).
- Kill and restart MarloweApp on startup if it has no available endpoints
> SCP-3792 restart marloweapp

- marlowe-playground-client/src/Marlowe/Linter.purs
- marlowe-playground-client/src/Marlowe/ViewPartials.purs
- marlowe-playground-client/src/Page/Simulation/BottomPanel.purs
- marlowe-playground-client/src/Page/Simulation/State.purs
- marlowe-playground-client/src/Page/Simulation/Types.purs
- marlowe-playground-client/src/Page/Simulation/View.purs
- marlowe-playground-client/src/Pretty.purs
- marlowe-playground-client/src/Simulator/Lenses.purs
- marlowe-playground-client/src/Simulator/State.purs
- marlowe-playground-client/src/Simulator/Types.purs
- marlowe-playground-client/src/StaticAnalysis/BottomPanel.purs
- marlowe-playground-client/static/css/utilities.css
- marlowe-playground-client/test/Marlowe/ContractTests.purs
- marlowe-playground-client/test/Marlowe/LintTests.purs
- web-common-marlowe/src/Examples/PureScript/CouponBondGuaranteed.purs
This PR adds some improvements to the simulator in general:
* ff4fd307c3ea4a57ea4db5fe38ba8540c6daee95 (individual commit already merged into sprint-54): Fixes the time entries in the transaction log that were using the Show instance.
* 22f8960f04d67d86c6a3ee043f67dbecb30336bb: Changes the MoveTo input to three different actions (move to next minute, next timeout, expiration time) and also fixes issue when simulating a Close contract directly should trigger the contract Start and End action at the same time.
* 6257f432f36830e9bc5979187279a738eaf16cf1 
* Removed basic Pretty.showPrettyMoney for humanizeValue (used in Run)
* Fixed reverse order in payments
* Fixed log scrolling
- Branch
- PR
> SCP-3585 transaction log improvements

- marlowe-playground-client/src/Component/MetadataTab/View.purs
This just updates the label to match the rest of the playground:
> SCP-3963 - Update metadata form to time parameters by their name

- marlowe-cli/run-tests.sh
I ran into problems with the `marlowe-cli/run-tests.sh` script when using wallet keys that also included staking, it was assuming no staking and generating an incorrect wallet address. It was suggested we modify the script to take explicit skey and address info instead of looking for the skey and vkey in hard-coded files in the `TREASURY` directory.
This ended up requiring some additional changes to how wallet keys are automatically created if they don't exist and some care to be taken in not clobbering a user's existing key files (which `cardano-cli` will cheerfully and silently do!)
Along the way I found some bugs and things that I went ahead and changed to work better or be clearer.
> SCP-3884 marlowe-cli/run-tests.sh should have better key handling 

- marlowe-playground-client/src/Marlowe/ViewPartials.purs
- marlowe-playground-client/src/StaticAnalysis/BottomPanel.purs
From the Jira issue:
> Static analysis result presumably prints the result of applying the “show” function to POSIX times and choice numbers, and the result is not very readable for users.
> 
> * POSIX time is printed as: (POSIXTime (Instant (Milliseconds __)))
> 
>   * It would be better to print them as a timestamp, something like: YYYY-MM-DD hh:mm:ss (timezone)
> 
> * Choice numbers are printed as: fromString "1"
> 
>   * It would be better to just print the number
With this PR
- Branch
- PR
> SCP-3965 improve output of static analysis

- marlowe-playground-client/src/Component/BottomPanel/View.purs
- marlowe-playground-client/src/Page/BlocklyEditor/BottomPanel.purs
- marlowe-playground-client/src/Page/BlocklyEditor/State.purs
- marlowe-playground-client/src/Page/BlocklyEditor/Types.purs
- marlowe-playground-client/src/Page/HaskellEditor/State.purs
- marlowe-playground-client/src/Page/HaskellEditor/Types.purs
- marlowe-playground-client/src/Page/HaskellEditor/View.purs
- marlowe-playground-client/src/Page/JavascriptEditor/State.purs
- marlowe-playground-client/src/Page/JavascriptEditor/Types.purs
- marlowe-playground-client/src/Page/JavascriptEditor/View.purs
- marlowe-playground-client/src/Page/MarloweEditor/BottomPanel.purs
- marlowe-playground-client/src/Page/MarloweEditor/State.purs
- marlowe-playground-client/src/Page/MarloweEditor/Types.purs
- marlowe-playground-client/src/Page/Simulation/BottomPanel.purs
- marlowe-playground-client/src/StaticAnalysis/BottomPanel.purs
- marlowe-playground-client/tailwind.config.js
This PR removes the need of the `Clear` button in the Static Analysis tool by always showing the template parameters on the  right of the panel, and by clearing the static analysis when the code or a template parameter changes.
This can be previewed in [this deploy](https://marlowe-playground-hernan.plutus.aws.iohkdev.io/#/).
Before
After
- Branch
- PR
> SCP-4066 Always show template parameters

- marlowe-playground-client/grammar.ne
- marlowe-playground-client/src/Marlowe/Parser.purs
This PR fixes an issue in the Blockly editor, where a warning that pointed to a Timeout crashed.
The problem was that we were using the `number` rule that doesn't have Position information instead of using the `%number` token that does.
The fix can be checked in [this deploy](https://marlowe-playground-hernan.plutus.aws.iohkdev.io/)
- Branch
- PR
> scp 4141 fix warning crash

- marlowe-playground-client/src/StaticAnalysis/Reachability.purs
Modify reachability static analysis so that it also flags when a `Close` contract is unreachable (not just non-trivial contracts)
Deployed to: https://marlowe-playground-pablo.plutus.aws.iohkdev.io/
> SCP-4067 - Make static analysis consider unreachable `Close` contracts

- marlowe-chain-sync/app/Options.hs
- marlowe-chain-sync/src/Language/Marlowe/Runtime/ChainSync/Api.hs
- marlowe-runtime/marlowe-follower/Main.hs
- marlowe-runtime/marlowe-history-cli/Main.hs
- marlowe-runtime/marlowe-history/Main.hs
- marlowe-runtime/marlowe-runtime.cabal
- marlowe-runtime/src/Language/Marlowe/Runtime/Core/Api.hs
- marlowe-runtime/src/Language/Marlowe/Runtime/History.hs
- marlowe-runtime/src/Language/Marlowe/Runtime/History/Api.hs
- marlowe-runtime/src/Language/Marlowe/Runtime/History/Follower.hs
- marlowe-runtime/src/Language/Marlowe/Runtime/History/FollowerSupervisor.hs
- marlowe-runtime/src/Language/Marlowe/Runtime/History/JobServer.hs
- marlowe-runtime/src/Language/Marlowe/Runtime/History/QueryServer.hs
- marlowe-runtime/test/Language/Marlowe/Runtime/History/FollowerSpec.hs
- nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-runtime.nix
- nix/pkgs/haskell/materialized-darwin/default.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-runtime.nix
- nix/pkgs/haskell/materialized-linux/default.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/marlowe-runtime.nix
- nix/pkgs/haskell/materialized-windows/default.nix
Changes included:
- Adds a new `marlowe-history` server process which manages multiple follower threads and exposes a query API and a command API (as well as a temporary repl)
- Adds a new `marlowe-history-cli` which can be used to communicate with a `marlowe-history` server. supported commands:
- `marlowe-history-cli add CONTRACT_ID` starts following a contract by its ID
- `marlowe-history-cli rm CONTRACT_ID` stops following a contract by its ID
- `marlowe-history-cli ls -[sf]` lists all followed contracts. `-s` shows the status of the follower and `-f` also shows failed contracts (e.g. if you use `add` and it fails to follow the contract, the failure message will be shown next to the contract ID with `-sf`)
> SCP-4277 Contract ID management

- marlowe/marlowe.cabal
- marlowe/test/Spec.hs
- marlowe/test/Spec/Marlowe/Marlowe.hs
- marlowe/test/Spec/Marlowe/Semantics/Functions.hs
- nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe.nix
- nix/pkgs/haskell/materialized-darwin/default.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe.nix
- nix/pkgs/haskell/materialized-linux/default.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/marlowe.nix
- nix/pkgs/haskell/materialized-windows/default.nix
This contains three testing-related changes:
1. SCP-4267 allows the false-positives static-analysis test to timeout without failing.
2. SCP-4269 confirms the warning message for zero payment.
3. SCP-4268 fixes a logical error in the test for `getContinuation`.
- Branch
- PR
> SCP-4267 SCP-4268 SCP-4269 Corrections to property-based tests

- marlowe-cli/examples/actus/run-actus.sh
- marlowe-cli/examples/cfd/run-cfd.sh
- marlowe-cli/examples/coveredCall/run-coveredCall.sh
- marlowe-cli/examples/escrow/run-confirm-claim.sh
- marlowe-cli/examples/escrow/run-confirm-problem.sh
- marlowe-cli/examples/escrow/run-dismiss-claim.sh
- marlowe-cli/examples/escrow/run-everything-is-alright.sh
- marlowe-cli/examples/simple/run-simple.sh
- marlowe-cli/examples/swap/run-swap.sh
- marlowe-cli/examples/zcb/run-zcb.sh
- marlowe-cli/run-nonpab-tests.sh
- marlowe-cli/src/Language/Marlowe/CLI/Run.hs
- marlowe-cli/test/double-satisfaction.sh
This work exposed an obscure bug in the way payee pkhs are used for
sorting, which has an effect on their tx index. bash code was added to
protect against this but tickets were created for further work in this
area at a later time.
- Branch
- PR
> SCP-4364 non-pab tests run again

- marlowe/debugging-cookbook.md
- marlowe/src/Language/Marlowe/Scripts.hs
- marlowe/test/Spec/Marlowe/Marlowe.hs
- marlowe/test/Spec/Marlowe/Plutus/Specification.hs
Changed the Marlowe semantics validator to forbid the creation of a new Marlowe contract in the same transaction as when another Marlowe contract closes.
- Branch
- PR
> SCP-4453 Validator now forbids close and creation in same tx.

- .stylish-haskell.yaml
This is a preliminary fix to remove the settings from stylish-haskell that were forcing column alignment on us in many parts of Haskell code. It also will not care about existing alignment in source files, which will minimize noisy changes to existing code.
> SCP-4454 Stop stylish-haskell from forcing alignment

- marlowe-runtime/marlowe-runtime.cabal
- marlowe-runtime/src/Language/Marlowe/Runtime/History/Api.hs
- marlowe-runtime/src/Language/Marlowe/Runtime/History/Store.hs
- marlowe-runtime/src/Language/Marlowe/Runtime/History/Store/Memory.hs
- marlowe-runtime/src/Language/Marlowe/Runtime/History/Store/Model.hs
- marlowe-runtime/test/Language/Marlowe/Runtime/History/Script.hs
- marlowe-runtime/test/Language/Marlowe/Runtime/History/Store/ModelSpec.hs
- marlowe-runtime/test/Language/Marlowe/Runtime/History/StoreSpec.hs
- marlowe-runtime/test/Language/Marlowe/Runtime/HistorySpec.hs
- nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-runtime.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-runtime.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/marlowe-runtime.nix
I wrote these tests by writing a pure model of the history store queries, writing property tests for that, then writing equivalence tests between the public API of the HistoryStore and the model.
The `HistoryScript` is a sequence of actions which create and advance contracts in a very simple mock of the blockchain, and which manipulate that mock by rolling it forwards and backwards. It has an `Arbitrary` instance that generates valid scripts. Using the script I can set up both the model store and the real store so that they have equivalent states. Once that is done, I can generate query parameters for the model and check them against both the real and the model implementation to make sure they produce the same result.
This will make it easy to test future implementations of the queries …
> SCP-4451 history tests

- marlowe-cli/marlowe-cli.cabal
- marlowe/marlowe.cabal
- marlowe/src/Language/Marlowe/Scripts.hs
- marlowe/test/Spec/Marlowe/Marlowe.hs
- marlowe/test/Spec/Marlowe/Plutus/Prelude.hs
- nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-cli.nix
- nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-cli.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/marlowe-cli.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/marlowe.nix
The `FIXME` regarding interval computations in the Marlowe semantics validator was addressed by converting open POSIX time intervals provided by Plutus to the closed interval required by Marlowe semantics. If an open interval is provided to the validator, then it is shrunk inward by 1 millisecond on the open side(s).
All on- and off-chain tests pass.
- Branch
- PR
> SCP-4150 SCP-4461 Fixed interval closure in validator.

- marlowe-chain-sync/example-client/FollowingUTxOs.hs
- marlowe-chain-sync/example-client/SkippingBlocks.hs
- marlowe-chain-sync/src/Language/Marlowe/Runtime/ChainSync/Api.hs
- marlowe-chain-sync/src/Language/Marlowe/Runtime/ChainSync/Server.hs
- marlowe-protocols/marlowe-protocols.cabal
- marlowe-protocols/src/Network/Protocol/ChainSeek/TH.hs
- marlowe-runtime/src/Language/Marlowe/Runtime/History/Follower.hs
- nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-protocols.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-protocols.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/marlowe-protocols.nix
Instead of relying on developers to manually update the schema version for the chain sync query every time it changes (which has so far never happened), this PR makes it so that it gets auto-generated as a hash of the type info of the query type. Note that it's not a deep traversal, it only inspects the surface-level type declaration (e.g. if one of the reference types changed, this would not change the schema version). This is better than nothing though, and changing the constructors in `Move` in any way will cause a new schema version to be generated.
> Use template haskell to generate a schema version from the query type

- README.adoc
The NixOS instructions were slightly outdated with deprecated fields. With this PR I can also demonstrate that I have correctly set up my PGP signature with git.
> SCP-4445: Update Readme with up to date NixOS instructions

- marlowe-runtime/marlowe-runtime.cabal
- marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/Constraints.hs
- marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/SystemStart.hs
- nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-runtime.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-runtime.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/marlowe-runtime.nix
Adds definitions, documentation, and API stubs for a Marlowe-specific transaction constraints module.
Future work:
- Implement `satisfiesConstraints` @paluh
- Implement `solveConstraints` @dino-iog
- Implement `buildCreateConstraints` @paluh @bjornkihlberg
- Implement `buildApplyInputsConstraints` @paluh @bjornkihlberg
- Implement `buildWithdrawConstraints` @paluh @bjornkihlberg
- Implement necessary support queries (fetch UTXOs for addresses, fetch application and payout script UTXOs) @jhbertra
> Add transaction constraints module

- marlowe/marlowe.cabal
- marlowe/src/Language/Marlowe/Core/V1/Semantics.hs
- marlowe/src/Language/Marlowe/Core/V1/Semantics/Types.hs
- marlowe/src/Language/Marlowe/Extended/V1.hs
- marlowe/src/Language/Marlowe/Extended/V1/Metadata/Types.hs
- marlowe/src/Language/Marlowe/ParserUtil.hs
- marlowe/test/Spec.hs
- marlowe/test/Spec/Marlowe/Marlowe.hs
- marlowe/test/Spec/Marlowe/Serialization.hs
- marlowe/test/Spec/Marlowe/Serialization/CoreJson.hs
- marlowe/test/Spec/Marlowe/Serialization/ExtendedJson.hs
- marlowe/test/Spec/Marlowe/Serialization/golden/swap-contract.json
- marlowe/test/Spec/Marlowe/Serialization/golden/swap-module.json
- nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe.nix
- nix/pkgs/haskell/materialized-darwin/default.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe.nix
- nix/pkgs/haskell/materialized-linux/default.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/marlowe.nix
- nix/pkgs/haskell/materialized-windows/default.nix
This PR is the same as [PR-192](https://github.com/input-output-hk/marlowe-cardano/pull/192) but in Haskell instead of PureScript. 
It adds a top-level construct in Marlowe Extended called `Module` that helps with adding a version number in the Json serialization and its the candidate to extend to add `imports/exports` in the future (hence the name), and also functions that can be converted to merkelized Marlowe Core.
This PR is related to the following MIP discussion: https://github.com/input-output-hk/MIPs/discussions/7 
I've also fixed the serialization of timeout to match the PureScript counterpart.
- Branch
- PR
> SCP-4319 Create top level Module construct in Extended

- marlowe-runtime/marlowe-follower/Main.hs
- marlowe-runtime/marlowe-history-cli/Main.hs
- marlowe-runtime/marlowe-tx/Main.hs
- marlowe-runtime/src/Language/Marlowe/Runtime/Core/Api.hs
- marlowe-runtime/src/Language/Marlowe/Runtime/History/Api.hs
- marlowe-runtime/src/Language/Marlowe/Runtime/History/Follower.hs
- marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/Api.hs
- marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/BuildConstraints.hs
- marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/Constraints.hs
- marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/Query.hs
- marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/Server.hs
- marlowe-runtime/test/Language/Marlowe/Runtime/History/FollowerSpec.hs
- marlowe-runtime/test/Language/Marlowe/Runtime/History/Script.hs
Implements one of the two queries needed for transaction creation. Also:
- Adds `address` and `assets` to `TransactionScriptOutput`
- Adds `address` to `Payout`
- Embeds a `TransacriontScriptoutput` inside `CreateStep`
> Implement LoadMarloweContext

- marlowe-chain-sync/marlowe-chain-sync.cabal
- marlowe-chain-sync/src/Language/Marlowe/Runtime/Cardano/Api.hs
- marlowe-chain-sync/src/Language/Marlowe/Runtime/Cardano/Feature.hs
- marlowe-chain-sync/src/Language/Marlowe/Runtime/ChainSync/Api.hs
- marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/Constraints.hs
- marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/Server.hs
- nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-chain-sync.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-chain-sync.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/marlowe-chain-sync.nix
Especially in transaction creation, we need to convert a lot between cardano API types and chain sync types. It's time we collected the functionality for doing so in a single location.
Since some of the types are era-dependent (further, they are feature-dependent), there are two ways to convert: regular conversion (via `HasCardanoType`) and feature-dependent conversion (via `HasFeatureDependentCardanoType`).
The `Feature` module abstracts away a lot of boilerplate that arises from using these era-dependent feature-proof objects. Now we can cast easily between them, extract the cardano era or shelley-based era, and try and obtain them from the era objects.
> Cardano Api <-> ChainSync.Api Conversion Functions

- marlowe-cli/src/Language/Marlowe/CLI/Command/Test.hs
- marlowe-cli/src/Language/Marlowe/CLI/Test.hs
- marlowe-cli/src/Language/Marlowe/CLI/Test/Script.hs
- marlowe-cli/src/Language/Marlowe/CLI/Test/Types.hs
- marlowe-cli/src/Language/Marlowe/CLI/Transaction.hs
> SCP-4465 add flag to control simulation mode for marlowe cli dsl

- marlowe-chain-sync/app/Main.hs
- marlowe-chain-sync/app/Options.hs
- marlowe-chain-sync/marlowe-chain-sync.cabal
- marlowe-chain-sync/src/Language/Marlowe/Runtime/ChainSync.hs
- marlowe-chain-sync/src/Language/Marlowe/Runtime/ChainSync/Api.hs
- marlowe-chain-sync/src/Language/Marlowe/Runtime/ChainSync/JobServer.hs
- nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-chain-sync.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-chain-sync.nix
- nix/pkgs/haskell/materialized-windows/.plan.nix/marlowe-chain-sync.nix
Adds a proxy API for node Tx submission to chainseekd. Something we might want to think about is how we want to handle node connections going forward. As it stands, `chainseekd` is becoming the node proxy for Marlowe Runtime. Is this what we want? Its name is a bit misleading if that is the case.
> Scp 4447 chainseek tx submission

- marlowe-runtime/cli/Language/Marlowe/Runtime/CLI/Command/Apply.hs
- marlowe-runtime/src/Language/Marlowe/Runtime/Core/Api.hs
- marlowe-runtime/test/Language/Marlowe/Runtime/History/FollowerSpec.hs
- marlowe-runtime/test/Language/Marlowe/Runtime/History/Script.hs
This PR fixes the type we use for the Redeemer in the Runtime for V1. It was incorrectly using `[Input]` when it needed to use `MarloweInput`.
> Use correct type for redeemer

- marlowe-runtime/config/Language/Marlowe/Runtime/CLI/Option.hs
- marlowe-runtime/marlowe-tx/Main.hs
Changed default for `--command-port` from `3720` to `3723` to avoid clash with chain seek's command port.
Updated Marlowe Runtime Client default port to match too
- Branch
- PR
> SCP-4488 - Fix collision in default marlowe-tx command port argument

- marlowe-cli/flake.lock
- marlowe-runtime/examples/create-many-utxos.ipynb
This is more than one utxo in each but all with ADA only.
The test script was made from a duplicate of the `create` Jupyter notebook with some modifications.
We can add a script to run several together if we want too like `marlowe-cli/examples` has.
> Added a create test with many utxos in the party addresses

- marlowe-chain-sync/src/Language/Marlowe/Runtime/ChainSync/Database/PostgreSQL.hs
- nix/dev/compose.nix
- packages.nix
Query was slow because it was filtering on the non-indexed `address` field. The index is on the MD5 hash of the address instead. Updated the `WHERE` clause of the query in question to take advantage of this, and added a comment to the file about this very non-obvious requirement for querying by address.
> Scp 4569 slow utxo query

- marlowe-runtime/cli/Language/Marlowe/Runtime/CLI/Command/Apply.hs
- marlowe-runtime/marlowe-runtime.cabal
- marlowe-runtime/marlowe-tx/Main.hs
- marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/Api.hs
- marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/BuildConstraints.hs
- marlowe-runtime/src/Language/Marlowe/Runtime/Transaction/Server.hs
- nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-runtime.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-runtime.nix
We were querying some protocol data at marlowe-tx server start and using it for the lifetime of the server, under the false assumption that it would remain unchanged. This PR updates `marlowe-tx` so that it re-queries this information every time it creates a new transaction.
Additionally, the way we were converting between timestamps and slots was broken. This PR fixes those conversions.
> Requery chain seek every transaction

- marlowe-protocols/src/Network/Protocol/ChainSeek/Codec.hs
- marlowe-protocols/src/Network/Protocol/ChainSeek/Types.hs
- marlowe-protocols/src/Network/Protocol/Job/Codec.hs
- marlowe-protocols/src/Network/Protocol/Job/Types.hs
- marlowe-protocols/src/Network/Protocol/Query/Codec.hs
- marlowe-protocols/src/Network/Protocol/Query/Types.hs
This allows us to drop `coerceTag` from `Codecs` modules.
- Branch
- PR
> Add kind annotations to `(Client|Server)HasAgency` constructors

- README.adoc
- nix/dev/compose.nix
> Update Dev Docker Compose Setup

- marlowe/specification/marlowe-cardano-specification.md
Added a "Constraint 0" to the Marlowe-Cardano specification, clarifying that the redeemer and script context map to the semantics input.
- Branch
- PR
> SCP-4566 Clarified relationship between redeemer and input in spec.

- marlowe-runtime/doc/deployment.md
> Add marlowe runtime apps to flake outputs

- marlowe-chain-sync/app/Main.hs
The reason for the failure simply needed to be displayed here. The config file was valid, but the genesis hash didn't match. The current message failed to adequately explain this.
> SCP-4809 Chainseek fails to read valid genesis file

- dev-shell.nix
- marlowe-chain-sync/api/Language/Marlowe/Runtime/ChainSync/Api.hs
- marlowe-chain-sync/example-client/FollowingUTxOs.hs
- marlowe-chain-sync/example-client/SkippingBlocks.hs
- marlowe-chain-sync/src/Language/Marlowe/Runtime/ChainSync/Server.hs
- marlowe-protocols-test/src/Test/Network/Protocol/ChainSeek.hs
- marlowe-protocols/src/Network/Protocol/ChainSeek/Client.hs
- marlowe-protocols/src/Network/Protocol/ChainSeek/Codec.hs
- marlowe-protocols/src/Network/Protocol/ChainSeek/Server.hs
- marlowe-protocols/src/Network/Protocol/ChainSeek/Types.hs
- marlowe-protocols/src/Network/Protocol/Job/Types.hs
- marlowe-runtime/discovery/Language/Marlowe/Runtime/Discovery/Chain.hs
- marlowe-runtime/history/Language/Marlowe/Runtime/History/Follower.hs
- marlowe-runtime/marlowe-tx/Logging.hs
- marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Chain.hs
- marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Submit.hs
Instead of the server holding agency and pushing updates to the client, the client gets agency and has to poll for updates when it is told to wait. This simplifies the job of the server, and it also gives the client the option to exit the protocol instead of wait.
> Give ChainSeek Client agency on Wait

- marlowe-chain-sync/chainseekd/Main.hs
- marlowe-runtime/doc/marlowe-tx.md
- marlowe-runtime/history-api/Language/Marlowe/Runtime/History/Api.hs
- marlowe-runtime/history/Language/Marlowe/Runtime/History/Follower.hs
- marlowe-runtime/marlowe-runtime.cabal
- marlowe-runtime/marlowe-tx/Logging.hs
- marlowe-runtime/marlowe-tx/Main.hs
- marlowe-runtime/tx-api/Language/Marlowe/Runtime/Transaction/Api.hs
- marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Query.hs
- marlowe-runtime/web-server/Language/Marlowe/Runtime/Web/Server/REST/Contracts.hs
- marlowe-runtime/web-server/Language/Marlowe/Runtime/Web/Server/REST/Transactions.hs
- nix/dev/compose.nix
- nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-runtime.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-runtime.nix
Explanation of cause: because the `MarloweContext` was being loaded from `marlowe-history`, there was a slight chance that it would still have stale information in it (i.e. the datum from before the previous transaction was confirmed), so it would try to match the inputs against the old datum and fail.
The fix was to load the MarloweContext directly from `chainseekd` instead. this guarantees that the data in the `MarloweContext` is at least as fresh as the data seen when the previous tx was confirmed. Note that this does _not_ guarantee it will work - if a rollback occurs between confirming the previous tx and building the next one, the same problem could happen. However, that isn't a bug - it's a legitimate case that might happen.
> SCP-4762 Erroneous `TEApplyNoMatchError` when applying inputs in Marlowe Runtime

- marlowe-runtime/cli/Language/Marlowe/Runtime/CLI/Command/Apply.hs
- marlowe-runtime/src/Language/Marlowe/Runtime/Core/Api.hs
- marlowe-runtime/test/Language/Marlowe/Runtime/History/FollowerSpec.hs
- marlowe-runtime/test/Language/Marlowe/Runtime/History/Script.hs
- marlowe-runtime/tx-api/Language/Marlowe/Runtime/Transaction/Api.hs
- marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/BuildConstraints.hs
- marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Server.hs
- marlowe-runtime/web-server-test/Spec.hs
- marlowe-runtime/web-server/Language/Marlowe/Runtime/Web/Server/DTO.hs
- marlowe-runtime/web-server/Language/Marlowe/Runtime/Web/Server/Monad.hs
- marlowe-runtime/web-server/Language/Marlowe/Runtime/Web/Server/REST/Transactions.hs
- marlowe-runtime/web-server/Language/Marlowe/Runtime/Web/Server/TxClient.hs
- marlowe-runtime/web/Language/Marlowe/Runtime/Web/Types.hs
- marlowe-scaling/src/Language/Marlowe/Runtime/Client/Build.hs
> SCP-4824 Enhanced Metadata Support

- marlowe-scaling/app/Main.hs
- marlowe-scaling/src/Language/Marlowe/Runtime/Client.hs
- marlowe-scaling/src/Language/Marlowe/Runtime/Client/Build.hs
- marlowe-scaling/src/Language/Marlowe/Runtime/Client/Run.hs
- marlowe-scaling/src/Language/Marlowe/Runtime/Client/Submit.hs
- marlowe-scaling/src/Language/Marlowe/Runtime/Client/Types.hs
Metadata support is added to the Marlowe Runtime client here, so that it can be used by [Marlowe Lambda](https://github.com/input-output-hk/marlowe-lambda).
- Branch
- PR
> SCP-4749 Added metadata support to scaling client

- marlowe-apps/src/Language/Marlowe/Runtime/App/Build.hs
- marlowe-apps/src/Language/Marlowe/Runtime/App/Types.hs
- marlowe-runtime/cli/Language/Marlowe/Runtime/CLI/Command/Apply.hs
- marlowe-runtime/cli/Language/Marlowe/Runtime/CLI/Command/Log.hs
- marlowe-runtime/history-api/Language/Marlowe/Runtime/History/Api.hs
- marlowe-runtime/marlowe-runtime.cabal
- marlowe-runtime/src/Language/Marlowe/Runtime/Core/Api.hs
- marlowe-runtime/test/Language/Marlowe/Runtime/History/FollowerSpec.hs
- marlowe-runtime/test/Language/Marlowe/Runtime/History/Script.hs
- marlowe-runtime/test/Language/Marlowe/Runtime/Transaction/BuildConstraintsSpec.hs
- marlowe-runtime/test/Language/Marlowe/Runtime/Transaction/ConstraintsSpec.hs
- marlowe-runtime/tx-api/Language/Marlowe/Runtime/Transaction/Api.hs
- marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/BuildConstraints.hs
- marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Constraints.hs
- marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Server.hs
- marlowe-runtime/web-server/Language/Marlowe/Runtime/Web/Server/DTO.hs
- marlowe-runtime/web-server/Language/Marlowe/Runtime/Web/Server/TxClient.hs
- nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-runtime.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-runtime.nix
> SCP-4855 Fix Misleading Redeemer Type in Runtime API

- README.adoc
- flake.nix
- packages.nix
This just adds the`marlowe-web-server` exe to the flake (Marlowe Runtime's REST Web Server)
- Branch
- (N/A) Tests are provided (if possible)
- (N/A) [Test report is updated](https://github.com/input-output-hk/marlowe-cardano/blob/main/marlowe/test/test-report.md) (if relevant)
- PR
> Add Marlowe Runtime Web Server to flake.nix

- marlowe-runtime/test/Language/Marlowe/Runtime/Transaction/ConstraintsSpec.hs
- marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Constraints.hs
Test case:
```bash
$MARLOWE_BIN/marlowe deposit \
--contract 2f8fba6ee73ae86b7d06813f2265ef2c8777b6737f0ef037db08e0c517569b63#1 \
--from-party addr_test1qp4zezsn0234wrdlkuxchus5fgtj3nprf25amdnedtad7t37akzcvrry0tv73kney9dkafq072p0dn8lmyvkwdth2res3205wz \
--to-party addr_test1qp4zezsn0234wrdlkuxchus5fgtj3nprf25amdnedtad7t37akzcvrry0tv73kney9dkafq072p0dn8lmyvkwdth2res3205wz --currency 4c666f86a731f72fa97c43fb00a52dd4d00519f4cad0d1389ad6f6d7 \
--token-name DollarThree \
--quantity 200 \
--validity-lower-bound 1673943329094 \
--validity-upper-bound 1673943569094 \
--change-address addr_test1qp4zezsn0234wrdlkuxchus5fgtj3nprf25amdnedtad7t37akzcvrry0tv73kney9dkafq072p0dn8lmyvkwdth2res3205wz \
--manual-sign tx.unsigned
```
Result before this commit:
```console
ApplyFailed …
```
> SCP-4932 Fixed erroneous `findMinUtxo` computation.

- marlowe/src/Language/Marlowe/Core/V1/Semantics/Types.hs
Now
```haskell
let
Just a = uncurry Address <$> deserialiseAddressBech32 "addr_test1vq9prvx8ufwutkwxx9cmmuuajaqmjqwujqlp9d8pvg6gupczgtm9j"
in
Pay (Role "peter") (Party a) (Token "" "") (Constant 10) Close
```
prints as
```haskell
Pay (Role "peter")
(Party (Address "addr_test1vq9prvx8ufwutkwxx9cmmuuajaqmjqwujqlp9d8pvg6gupczgtm9j"))
(Token "" "")
(Constant 10) Close
```
- Branch
- PR
> SCP-4518 Fixed pretty printing of parties.

- marlowe-runtime/test/Language/Marlowe/Runtime/Transaction/ConstraintsSpec.hs
Found a bug where invalid wallets were being created for some tests intermittantly because of a collision in generating TxOutRef values. Fixed.
> Fixed bug where WalletContext was missing assets

- marlowe-apps/Finder.md
- marlowe-apps/Oracle.md
- marlowe-apps/Scaling.md
- marlowe-apps/marlowe-apps.cabal
- marlowe-apps/src/Language/Marlowe/Runtime/App/Parser.hs
- marlowe-apps/src/Language/Marlowe/Runtime/App/Transact.hs
- marlowe-apps/src/Language/Marlowe/Runtime/App/Types.hs
- nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-apps.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-apps.nix
The following parameters were added to `marlowe-scaling`:
- delay before building transaction
- delay after transaction is confirmed
- jittering of delays
- retry with backoff
- Branch
- PR
> SCP-4883 ΔQ enhancements for `marlowe-scaling` client

- marlowe-runtime/indexer-test/Language/Marlowe/Runtime/Indexer/MarloweUTxOSpec.hs
- marlowe-runtime/marlowe-runtime.cabal
- nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-runtime.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-runtime.nix
Some tech debt cleanup in MarloweUTxOSpec to use `gen` library where possible.
> Use new arbitrary instances in indexer-test

- marlowe-cli/marlowe-cli.cabal
- marlowe-cli/src/Language/Marlowe/CLI/Command/Contract.hs
- marlowe-cli/src/Language/Marlowe/CLI/Plutus/Script/Utils.hs
- marlowe/marlowe-cardano.cabal
- marlowe/src/Language/Marlowe/Scripts.hs
- nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-cardano.nix
- nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-cli.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-cardano.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-cli.nix
This adds two commands to `marlowe-cli`:
- `marlowe-cli contract pir` prints the Plutus Intermediate Representation (PIR) of the Marlowe validator.
- `marlowe-cli contract uplc` prints the Untyped Plutus Core (UPLC) of the Marlowe validator.
- Branch
- PR
> SCP-4588 Added commands for print PIR and UPLC.

- marlowe-chain-sync/chain-indexer/Language/Marlowe/Runtime/ChainIndexer/Database/PostgreSQL.hs
We verified with Jared the interpretation of the Babbage spec that collateral change outputs have index 1.
Tested via comparing that the comparison of `marlowe-chain-indexer` vs `cardano-db-sync` no longer has discrepancies and collateral change output on `preview` and and `preprod`.
- Branch
- PR
> SCP-4864 Fixed collateral change output index, per Babbage spec.

- marlowe-chain-sync/chain-indexer/Language/Marlowe/Runtime/ChainIndexer/Database/PostgreSQL.hs
- marlowe-chain-sync/chain-indexer/Language/Marlowe/Runtime/ChainIndexer/NodeClient.hs
- marlowe-chain-sync/chainseekd/Logging.hs
- marlowe-chain-sync/libchainseek/Language/Marlowe/Runtime/ChainSync/QueryServer.hs
- marlowe-chain-sync/libchainseek/Language/Marlowe/Runtime/ChainSync/Server.hs
- marlowe-chain-sync/marlowe-chain-indexer/Logging.hs
- marlowe-chain-sync/marlowe-chain-sync.cabal
- marlowe-test/chain/compare.sh
- marlowe-test/chain/compare.sql
- nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-chain-sync.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-chain-sync.nix
Round-trip serialization of CBOR was corrupting some datums and their hashes. This fix retries the bytes directly from the ledger, instead of via `Cardano.Api`.
Tested by `marlowe-test/chain/comparison.sh` to compare `marlowe-chain-indexer` vs `cardano-db-sync` on both the `preview` and `preprod` networks. There was a 100% match.
- Branch
- PR
> SCP-4863 Corrected datum and its hash in chain index

- marlowe-integration/app/Main.hs
- marlowe-integration/marlowe-integration.cabal
- marlowe-integration/src/Test/Integration/Marlowe/Local.hs
- marlowe-runtime/marlowe-runtime.cabal
- marlowe-runtime/web/Language/Marlowe/Runtime/Web/API.hs
- marlowe-runtime/web/Language/Marlowe/Runtime/Web/Client.hs
- marlowe-runtime/web/Language/Marlowe/Runtime/Web/Types.hs
- nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-integration.nix
- nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-runtime.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-integration.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-runtime.nix
- Adds a client module to the `web` library
- Adds a web server to the `marlowe-integration` container
- Adds a client runner function to the `MarloweRuntime` record
- Rewites the `marlowe-integration` example app to use the web API instead.
> SCP-5020 web test setup

- marlowe-runtime/marlowe-indexer/deploy/rollback.sql
Fixing typo in constraint name in rollback migration.
- Branch
- PR
> fix typo in drop constraint command

- marlowe-chain-sync/chain-indexer/Language/Marlowe/Runtime/ChainIndexer/Database/PostgreSQL.hs
- marlowe-chain-sync/deploy/fix-collateral-index.sql
- marlowe-chain-sync/revert/fix-collateral-index.sql
- marlowe-chain-sync/sqitch.plan
- marlowe-chain-sync/verify/fix-collateral-index.sql
- marlowe-test/chain/compare.sql
The output index of collateral change is now correctly computed according to the ledger rules. The `marlowe-chain-indexer` vs `cardano-db-sync` comparison test passes on both `preprod` and `preview`:
```console
Table   | Count of ChainIndex Minus DbSync | Count of DbSync Minus ChainIndex | Discrepancies? 
-----------+----------------------------------+----------------------------------+----------------
block     |                                0 |                                0 | f
tx        |                                0 |                                0 | f
metadata  |                                0 |                                0 | f
txout     |                                0 |                                0 | f
datum     |                                0 | …
```
> SCP-5031 Fixed collateral indexing for invalid scripts.

- marlowe-apps/Pipe.md
- marlowe-apps/ReadMe.md
- marlowe-apps/marlowe-apps.cabal
- marlowe-apps/pipe/Main.hs
- nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-apps.nix
- nix/pkgs/haskell/materialized-darwin/default.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-apps.nix
- nix/pkgs/haskell/materialized-linux/default.nix
This commit simply migrates the `exe:marlowe-pipe` from https://github.com/input-output-hk/marlowe-lambda to `marlowe-apps/marlowe-apps.cabal`.
- Branch
- PR
> SCP-5044 Migrated `marlowe-pipe` from `marlowe-lambda` repo.

- marlowe-cli/marlowe-cli.cabal
- marlowe-cli/src/Language/Marlowe/CLI/Command.hs
- marlowe-cli/src/Language/Marlowe/CLI/Command/Util.hs
- marlowe-cli/src/Language/Marlowe/CLI/Orphans.hs
- marlowe-cli/src/Language/Marlowe/CLI/Plutus/Script/Utils.hs
- nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-cli.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-cli.nix
Before:
```console
marlowe-cli : a command-line tool for Marlowe contracts
Usage: marlowe-cli [--version] 
(COMMAND | COMMAND | [--alonzo-era] (COMMAND | COMMAND) | 
--babbage-era (COMMAND | COMMAND))
Utilities for Marlowe.
Available options:
-h,--help                Show this help text
--version                Show version.
--alonzo-era             Read and write Alonzo transactions
--babbage-era            Read and write Babbage transactions
High-level commands:
run                      Run a contract.
template                 Create a contract from a template.
test                     Test contracts.
Low-level commands:
contract                 Export contract address, validator, datum, or
redeemer.
input                    Create inputs to a contract.
role                     Export …
```
> SCP-4410 Removed triple repetition of help text from marlowe-cli.

- marlowe-chain-sync/chainseekd/Main.hs
- marlowe-chain-sync/libchainseek/Language/Marlowe/Runtime/ChainSync/Database/PostgreSQL.hs
- marlowe-integration/src/Test/Integration/Marlowe/Local.hs
The query functions `performFindTxsFor` and `performFindTxsAt` in `Language.Marlowe.Runtime.ChainSync.Database.PostgreSQL` were hardwired for testnets only: they ignored the [CIP-19 network binary tag](https://cips.cardano.org/cips/cip19/#binaryformat) for `mainnet`. This commit fixes the network tag for these two functions.
Tested manually on `mainnet` by comparing the output of `marlowe-pipe` to public explorers.
- Branch
- PR
> SCP-5057 Fixed CIP-19 network tag for `FindTxsTo` and `FindTxsFor`.

- marlowe-runtime/test/Language/Marlowe/Runtime/Transaction/BuildConstraintsSpec.hs
- marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/BuildConstraints.hs
Fix bug in computation of validity interval for a timed-out transaction, and added corresponding unit test.
Review tasks:
Tested:
- 1,000,000 replications of property-based test.
- Branch
- PR
> SCP-4817 Fix and unit test for timed-out validity interval computation.

- marlowe-test/src/Spec/Marlowe/Service.hs
- marlowe-test/src/Spec/Marlowe/Service/Types.hs
- marlowe/src/Language/Marlowe/Core/V1/Semantics/Types.hs
This PR implements the `EvalValue` command added to the spec test tool in [this PR](https://github.com/input-output-hk/marlowe/pull/160)
- Branch
- PR
> SCP-4901 - Add EvalValue command to spec client

- marlowe-integration-tests/README.md
- marlowe-integration/README.md
I wrote a `README.md` for `marlowe-integration-tests` and later realised one already existed in `marlowe-integration`, so I used mine to extend the existing one, and also added a small one to `marlowe-integration-tests` that gives minimal instructions and points to the general one.
Also couple of typographical fixes.
- PR
> Create README.md for marlowe-integration-tests and extend it for marlowe-integration

- marlowe-runtime/indexer/Language/Marlowe/Runtime/Indexer/Database/PostgreSQL/CommitBlocks.hs
Here is an issue that impacts `marlowe-indexer` when the node rolls back to genesis. Old blocks get marked as rolled back to Genesis, but these are not removed when adding the blocks back later.
- Branch
- PR
> Delete rollback blocks when saving blocks

- marlowe-chain-sync/chain-indexer/Language/Marlowe/Runtime/ChainIndexer/Database/PostgreSQL.hs
- marlowe-test/chain/compare.sh
- marlowe-test/chain/compare.sql
I upgraded the `marlowe-chain-indexer` vs `cardano-db-sync` comparison test to account for epoch-boundary blocks (EBBs) on `mainnet`. I also added a comment in the PostgreSQL code noting the existence of EBBs.
The comparison tests at aff3683e0ff3281ef76b03177afec66e3665510c passed (for blocks) and are recorded at http://testing.marlowe.run/database/. We still have unrelated comparison failures for `mainnet` only.
- Branch
- PR
> SCP-5054 Handle epoch-boundary block in chain-indexer tests

- marlowe-test/chain/compare.sql
The mainnet ledger contains one transaction output with illegal bytes for the Shelley address. The database-comparison tests are modified to ignore this irrelevant failure.
- Branch
- PR
> SCP-5116 Fix db-comparison for illegal Shelley address

- marlowe-test/chain/compare.sql
Revised the asset-out comparison query to handle larger tables. (Mainnet now has 550M+ asset outputs now.)
- Branch
- PR
> SCP-5096 Rewrote asset-out comparison query.

- cabal.project
- marlowe-test/src/Spec/Marlowe/Service.hs
- marlowe-test/src/Spec/Marlowe/Service/Random.hs
- marlowe-test/src/Spec/Marlowe/Service/Types.hs
- nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-spec-test.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-spec-test.nix
Introduced `seed` and `size` parameters for  `generate-random-value` request in the marlowe-test-spec.
- Branch
- PR
> SCP-5110: Reproducible tests 

- marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/MarloweQuery.hs
- marlowe-runtime/marlowe-indexer/deploy/indexRoleCurrency.sql
- marlowe-runtime/marlowe-indexer/revert/indexRoleCurrency.sql
- marlowe-runtime/marlowe-indexer/sqitch.plan
- marlowe-runtime/marlowe-indexer/verify/indexRoleCurrency.sql
- marlowe-runtime/sync-api/Language/Marlowe/Protocol/Query/Client.hs
- marlowe-runtime/sync-api/Language/Marlowe/Protocol/Query/Server.hs
- marlowe-runtime/sync-api/Language/Marlowe/Protocol/Query/Types.hs
- marlowe-runtime/sync/Language/Marlowe/Runtime/Sync/Database.hs
- marlowe-runtime/sync/Language/Marlowe/Runtime/Sync/Database/PostgreSQL.hs
- marlowe-runtime/sync/Language/Marlowe/Runtime/Sync/Database/PostgreSQL/GetHeaders.hs
- marlowe-runtime/sync/Language/Marlowe/Runtime/Sync/Database/PostgreSQL/GetWithdrawal.hs
- marlowe-runtime/sync/Language/Marlowe/Runtime/Sync/Database/PostgreSQL/GetWithdrawals.hs
- marlowe-runtime/test/Language/Marlowe/Protocol/QuerySpec.hs
Changes the parameters of the `GetWithdrawals` query in the following ways:
1. The query is now paginated (it accepts a `Range` and returns a `Page`).
2. The query accepts a `Set PolicyId` to filter by role token currencies. Empty set => no filtering.
- Branch
- PR
> SCP-5132 Withdrawal query changes

- marlowe-test/marlowe-test.cabal
- marlowe-test/src/Spec/Marlowe/Plutus.hs
- marlowe-test/src/Spec/Marlowe/Plutus/MList.hs
- marlowe/CHANGELOG.md
- marlowe/marlowe-cardano.cabal
- marlowe/specification/marlowe-cardano-specification.md
- marlowe/src/Language/Marlowe/Core/V1/Semantics.hs
- nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-cardano.nix
- nix/pkgs/haskell/materialized-darwin/.plan.nix/marlowe-test.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-cardano.nix
- nix/pkgs/haskell/materialized-linux/.plan.nix/marlowe-test.nix
1. Discussion and justification for using `PlutusTx.AssocMap` instead of Isabelle's `MList` were added as comments to all usages in Marlowe's semantics implementation.
2. A paragraph was added to the Marlowe-Cardano specification about `MList`.
3. Property-based tests were added for all `AssocMap` functions used the Marlowe validator, to verify that if there are no duplicates entries and the `MList` is sorted, then the behavior matches `AssocMap`.
4. The change log was updated.
***Reviewers: Does this adequately address the following audit findings?***
- Branch
- PR
> SCP-5126 MList annotations and tests

- marlowe/CHANGELOG.md
- marlowe/src/Language/Marlowe/Core/V1/Semantics.hs
- marlowe/src/Language/Marlowe/Core/V1/Semantics/Types.hs
Added the missing equality test for `ReduceAssertionFailed`. Note that this does not affect the Marlowe validators.
***Reviewers: Does this adequately address the following audit findings?***
- Branch
- PR
> SCP-5129 Fixed `(==)` for `ReduceAssertionFailed`.

- marlowe/CHANGELOG.md
- marlowe/specification/marlowe-cardano-specification.md
- marlowe/src/Language/Marlowe/Scripts.hs
1. Added comment to validator about why a payment to an address may be split in several outputs.
2. Added similar comment to the Marlowe-Cardano specification.
3. Also update the change log.
***Reviewers: Does this adequately address the following audit findings?***
- Branch
- PR
> SCP-5128 Commented on rationale for allowing multiple outputs to an address

- deploy/operables.nix
- eventuo11y-extras/README.md
- eventuo11y-extras/src/Observe/Event/Backend/Extra.hs
- eventuo11y-extras/src/Observe/Event/Component.hs
- marlowe-chain-sync/README.md
- marlowe-chain-sync/libchainsync/Language/Marlowe/Runtime/ChainSync/NodeClient.hs
- marlowe-chain-sync/marlowe-chain-indexer/Logging.hs
- marlowe-chain-sync/marlowe-chain-indexer/Options.hs
- marlowe-chain-sync/marlowe-chain-sync.cabal
- marlowe-chain-sync/marlowe-chain-sync/Logging.hs
- marlowe-chain-sync/marlowe-chain-sync/Options.hs
- marlowe-protocols/src/Network/Protocol/Connection.hs
- marlowe-runtime/doc/ReadMe.md
- marlowe-runtime/marlowe-indexer/Logging.hs
- marlowe-runtime/marlowe-indexer/Main.hs
- marlowe-runtime/marlowe-proxy/Logging.hs
- marlowe-runtime/marlowe-proxy/Main.hs
- marlowe-runtime/marlowe-runtime.cabal
- marlowe-runtime/marlowe-sync/Logging.hs
- marlowe-runtime/marlowe-sync/Main.hs
- marlowe-runtime/marlowe-tx/Logging.hs
- marlowe-runtime/marlowe-tx/Main.hs
> PLT-5286 Adjust default logging configuration for each component and document

- marlowe/src/Language/Marlowe/Core/V1/Semantics/Types.hs
This addresses the following audit-report comment:
> The equality of cases for the `When` constructor would be
> simplified by using `cases1 == cases2`. If there is a reason
> for the more verbose equality condition, it should be outlined
> in a comment.
- Branch
- PR
> PLT-3382 Added comment on `When` equality test.

- deploy/operables.nix
The OCI images incorrectly had set `CARDANO_TESTNET_MAGIC` when the network ID was `mainnet`. This meant that `marlowe-indexer` did not populate the `marlowe` schema because `marlowe-chain-sync` could not detect Marlowe scripts due to an incorrect network mask.
- Branch
- PR
> PLT-5491 Fixed testnet magic detection in OCI operables.

- marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/GetContracts.hs
- marlowe-integration/app/Main.hs
- marlowe-runtime-web/changelog.d/20230417_165332_tomasz.rybarczyk_SCP_4926_cip30_friendly_web_server.md
- marlowe-runtime-web/changelog.d/scriv.ini
- marlowe-runtime-web/marlowe-runtime-web.cabal
- marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/DTO.hs
- marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/REST/ApiError.hs
- marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/REST/Contracts.hs
- marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/REST/Transactions.hs
- marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/REST/Withdrawals.hs
- marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/Util.hs
- marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/API.hs
- marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/Client.hs
- marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/Types.hs
- marlowe-runtime-web/test/Spec.hs
This change adds an alternative flow to the transaction submission:
* if the user provides an accept header to the `post`: "application/vendor.iog.marlowe-runtime.create-tx-json" we return back an `tx` text envelope instead of `txBody`.
* `put` endpoint is able to accept now both `tx` or `TxWitness`
- Branch
- PR
> Introduce "CIP-30 friendly" flow for contracts to the REST API

- marlowe-test/marlowe-test.cabal
- marlowe-test/src/Spec/Marlowe/Marlowe.hs
- marlowe-test/src/Spec/Marlowe/Plutus/Specification.hs
- marlowe/CHANGELOG.md
- marlowe/changelog.d/20230418_154551_brian.bush_PLT_5462.md
- marlowe/marlowe-cardano.cabal
- marlowe/src/Language/Marlowe/Scripts.hs
This PR adds a cabal flag `--flag trace-plutus` for the `marlowe-cardano` and `marlowe-test` packages. In production this flag should not be set because it enlarges the validator and changes its hash. If the flag is turned on, however, the test suite `test:marlowe-test` will check the Plutus logs to see that the correct error is occurring in cases where the validator should fail.
With this flag turned on, 10,000 repetitions of the semantics validator tests all passed. We need to discuss whether to turn on this flag in the CI, or just run it nightly. In any case, that will be a separate PR.
This flag is also useful in `marlowe-cli` for creating a tracing validator for on-chain usage.
- Branch
- PR
> PLT-5462 Check Plutus logs in validator tests

- marlowe-integration-tests/test/Language/Marlowe/Runtime/CliSpec.hs
- marlowe-runtime-cli/app/Language/Marlowe/Runtime/CLI/Command/Apply.hs
- marlowe-runtime/changelog.d/20230503_170553_bjorn.wilhelm.kihlberg_PLT_4173.md
This ticket runs `JobClient` and the **Marlowe Runtime CLI** and compares their results to check that they are the same. The ticket is currently implementing a simple example based suite. Property testing might not work because the mechanisms tested are too slow (There might be an interesting opportunity to do this anyway in order to seek out opportunities for performance optimization).
- Currently the comparison between these two mechanisms are not comparing everything that it could. This is because there's a record called `TxBodyRaw` that has a field `_vldt` that is not deterministic between tests. I haven't yet gotten around to figuring out how to inspect this record as it seems to be a cleverly generated type.
- I am not comparing results of `advance`.
- Branch
- …
> PLT-4173: E2E CLI tests

- deploy/operables.nix
A comment that wasn't commented out in the docker images has been causing `/bin/entrypoint` to fail for the Marlowe Runtime docker images.
- Branch
- PR
> PLT-5957 Fixed uncommented comments in operables derivation.

- marlowe-test/src/Spec/Marlowe/Plutus/Arbitrary.hs
- marlowe-test/src/Spec/Marlowe/Semantics/Arbitrary.hs
- marlowe-test/src/Spec/Marlowe/Semantics/Compute.hs
- marlowe-test/src/Spec/Marlowe/Semantics/Entropy.hs
Did a sweep of `Spec.Marlowe.Semantics.Arbitrary` to improve the instances. Changes mostly focused on:
1. Simplifying overly complex generation logic
2. Making proper use of the `size` parameter
3. Avoiding the use of `suchThat` where possible
4. Fixing incorrectly-written `shrink` implementations (can make a huge difference in performance)
I have annotated my changes with their rationale in the PR.
- Branch
- PR
> Improve semantics arbitrarty intances

- deploy/nomadTasks.nix
- deploy/operables.nix
- marlowe-integration-tests/marlowe-integration-tests.cabal
- marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/Basic.hs
- marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/Contract.hs
- marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/StandardContract.hs
- marlowe-integration/src/Test/Integration/Marlowe/Local.hs
- marlowe-runtime/changelog.d/20230531_163411_jhbertra_plt_5850_get_merkleized_inputs.md
- marlowe-runtime/contract-api/Language/Marlowe/Runtime/Contract/Api.hs
- marlowe-runtime/contract/Language/Marlowe/Runtime/Contract/QueryServer.hs
- marlowe-runtime/contract/Language/Marlowe/Runtime/Contract/Store.hs
- marlowe-runtime/contract/Language/Marlowe/Runtime/Contract/Store/File.hs
- marlowe-runtime/contract/Language/Marlowe/Runtime/Contract/Store/Memory.hs
- marlowe-runtime/marlowe-contract/Logging.hs
- marlowe-runtime/marlowe-runtime.cabal
- marlowe-runtime/marlowe-tx/Logging.hs
- marlowe-runtime/marlowe-tx/Main.hs
- marlowe-runtime/src/Language/Marlowe/Runtime/Core/Api.hs
- marlowe-runtime/test/Language/Marlowe/Runtime/Transaction/BuildConstraintsSpec.hs
- marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction.hs
- marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/BuildConstraints.hs
- marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Safety.hs
- marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Server.hs
- marlowe-test/marlowe-test.cabal
- marlowe-test/src/Spec/Marlowe/Semantics.hs
- marlowe-test/src/Spec/Marlowe/Semantics/Arbitrary.hs
- marlowe-test/src/Spec/Marlowe/Semantics/Path.hs
- marlowe-test/test/Spec.hs
- marlowe/src/Language/Marlowe/Core/V1/Semantics.hs
- nix/dev/compose.nix
> PLT-5850 Merkleize Inputs query

- marlowe-apps/src/Language/Marlowe/Runtime/App/Build.hs
- marlowe-cli/cli-test/Language/Marlowe/CLI/Test/Runtime/Interpret.hs
- marlowe-client/src/Control/Monad/Trans/Marlowe/Class.hs
- marlowe-integration-tests/test/Language/Marlowe/Runtime/CliSpec.hs
- marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/ApplyInputs.hs
- marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/Create.hs
- marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/StandardContract.hs
- marlowe-runtime-cli/app/Language/Marlowe/Runtime/CLI/Command/Create.hs
- marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/REST/ApiError.hs
- marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/TxClient.hs
- marlowe-runtime/changelog.d/20230601_161758_jhbertra_plt_5854_create_by_hash.md
- marlowe-runtime/tx-api/Language/Marlowe/Runtime/Transaction/Api.hs
- marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Server.hs
> PLT-5854 create by hash

- marlowe-apps/changelog.d/20230603_174929_brian.bush_PLT_6142.rst
- marlowe-apps/src/Language/Marlowe/Runtime/App.hs
- marlowe-apps/src/Language/Marlowe/Runtime/App/Submit.hs
- marlowe-apps/src/Language/Marlowe/Runtime/App/Transact.hs
- marlowe-apps/src/Language/Marlowe/Runtime/App/Types.hs
This switches transaction submission in `marlowe-apps` to use `marlowe-tx` instead of `marlowe-chain-sync`.
- Branch
- PR
> PLT-6142 Fixed transaction submission in `marlowe-apps`

- nix/marlowe-cardano/compose.nix
A tiny fix which bumps marlowe version in the docker compose nix expression.
> Fix docker compose marlowe version

- marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/DTO.hs
No changelog required because the issue is not in a release.
> use correct timestamps in status headers

- marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/Common.hs
- marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/Contracts/Contract/Post.hs
- marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/Contracts/Contract/Put.hs
- marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/Contracts/Transactions/Transaction/Post.hs
- marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/Contracts/Transactions/Transaction/Put.hs
- marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/StandardContract.hs
- marlowe-integration/app/Main.hs
- marlowe-runtime-cli/app/Language/Marlowe/Runtime/CLI/Command/Create.hs
- marlowe-runtime-web/changelog.d/20230630_110941_brian.bush_PLT_6335.md
- marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/DTO.hs
- marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/REST/Contracts.hs
- marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/API.hs
- marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/Client.hs
- marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/Types.hs
- marlowe-runtime-web/test/Spec.hs
- marlowe-runtime/changelog.d/20230630_091216_brian.bush_PLT_6335.md
Implemented including stake credentials in the Marlowe validator address in the following clients:
- `marlowe-runtime-cli create`
- Contract creation in REST API
Tested manually on the `preprod` network.
- Branch
- PR
> PLT-6335 Added stake-address support for `marlowe-runtime-cli` and REST API

- marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/StandardContract.hs
- marlowe-integration-tests/test/Language/Marlowe/Runtime/WebSpec.hs
- marlowe-runtime-web/marlowe-runtime-web.cabal
- marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server.hs
- marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/ContractClient.hs
- marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/Monad.hs
- marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/REST/ContractSources.hs
- marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/API.hs
- marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/Client.hs
- marlowe-runtime/changelog.d/20230713_102217_jhbertra_plt_6343_get_contract_sources.md
Adds a few new endpoints with `GET` methods:
- `/contracts/sources/:contractSourceId`
- `/contracts/sources/:contractSourceId/adjacency`
- `/contracts/sources/:contractSourceId/closure`
- Branch
- PR
> PLT-6343 GET APIs for Contract Sources

- marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/Common.hs
- marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/Contracts/Contract/Post.hs
- marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/Contracts/Contract/Put.hs
- marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/Contracts/Transactions/Transaction/Post.hs
- marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/Contracts/Transactions/Transaction/Put.hs
- marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/StandardContract.hs
- marlowe-integration/app/Main.hs
- marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/REST/ContractSources.hs
- marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/REST/Contracts.hs
- marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/TxClient.hs
- marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/Types.hs
- marlowe-runtime-web/test/Spec.hs
- marlowe-runtime/changelog.d/20230714_084746_jhbertra_plt_6344_get_contract_source_tx.md
Added ability to specify a `contractSourceId` when creating a contract.
- Branch
- PR
> PLT-6344 Add contract source ID option to `POST /contracts`

- marlowe-chain-sync/.golden/ChainSeek/golden
- marlowe-chain-sync/libchainsync/Language/Marlowe/Runtime/ChainSync.hs
- marlowe-chain-sync/libchainsync/Language/Marlowe/Runtime/ChainSync/Database.hs
- marlowe-chain-sync/libchainsync/Language/Marlowe/Runtime/ChainSync/Database/PostgreSQL.hs
- marlowe-chain-sync/libchainsync/Language/Marlowe/Runtime/ChainSync/Server.hs
- marlowe-chain-sync/marlowe-chain-sync/Main.hs
- marlowe-protocols/src/Network/Protocol/ChainSeek/Client.hs
- marlowe-protocols/src/Network/Protocol/ChainSeek/Server.hs
- marlowe-protocols/src/Network/Protocol/ChainSeek/Types.hs
- marlowe-runtime/changelog.d/20230725_142448_jhbertra_plt_6838_optimise_chainseek.md
- marlowe-runtime/indexer/Language/Marlowe/Runtime/Indexer/ChainSeekClient.hs
- marlowe-runtime/indexer/Language/Marlowe/Runtime/Indexer/Database/PostgreSQL/CommitBlocks.hs
- marlowe-runtime/runtime/Language/Marlowe/Runtime.hs
- nix/marlowe-cardano/compose.nix
- nix/shell.nix
- Time to sync (against fully synced chain DB) on the order of 1 minute
- Time to sync (against fully synced chain DB) on the order of 5 minutes
- Time to sync (against fully synced chain DB) __
- Branch
- PR
> PLT-6838 Optimise ChainSeek

- marlowe-runtime/changelog.d/20230803_091230_brian.bush_PLT_7027.md
- marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Constraints.hs
Instead of rounding the maximum Plutus cost, use the ceiling function.
- Branch
- PR
> PLT-7027 Round maximum execution fee upward.

- marlowe-runtime/changelog.d/20230808_154617_brian.bush_PLT_6849.md
- marlowe-runtime/test/Language/Marlowe/Runtime/Transaction/SafetySpec.hs
- marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Safety.hs
- marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Server.hs
The safety checks were using inconsistent system history because this was obtained both locally in `checkTransaction` and separately from its `solveConstraints` argument. This is fixed by using the same system history for both building constraints and solving them.
- Branch
- PR
> PLT-6849 Fixed inconsistency in system history for safety checks.

- marlowe-runtime-web/changelog.d/20230907_083927_yves.hauser_PLT_5723.md
- marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/REST/ApiError.hs
This PR introduces the use of generics with error messages: As error code the name of the data constructor is used.
- Branch
- PR
> PLT-5723: REST error reporting

- .github/workflows/deploy.yml
- marlowe-apps/changelog.d/20230616_104735_brian.bush_PLT_6224.md
- marlowe-apps/changelog.d/20230629_185547_brian.bush_PLT_5726.md
- marlowe-apps/changelog.d/20230629_185547_brian.bush_PLT_5726.rst
- marlowe-apps/changelog.d/20230920_162407_jhbertra_plt_7566_marlowe_apps_images.md
- marlowe-apps/changelog.d/scriv.ini
- marlowe-apps/marlowe-apps.cabal
- marlowe-apps/src/Language/Marlowe/Runtime/App/Parser.hs
- marlowe-apps/src/Language/Marlowe/Runtime/App/Run.hs
- marlowe-apps/src/Language/Marlowe/Runtime/App/Submit.hs
- marlowe-apps/src/Language/Marlowe/Runtime/App/Types.hs
- marlowe-cli/changelog.d/20230921_101638_jhbertra_plt_7566_marlowe_apps_images.md
- marlowe-cli/cli-test/Language/Marlowe/CLI/Test/Runner.hs
- marlowe-cli/cli-test/Language/Marlowe/CLI/Test/Types.hs
- marlowe-cli/command/Language/Marlowe/CLI/Command/Test.hs
- marlowe-cli/marlowe-cli.cabal
- nix/marlowe-cardano/deploy/oci-images.nix
- nix/marlowe-cardano/deploy/operables.nix
> PLT-7566 Add docker images for marlowe-apps

- marlowe-apps/changelog.d/20230918_161023_brian.bush_PLT_7288.rst
- marlowe-apps/src/Language/Marlowe/Runtime/App/Channel.hs
- marlowe-apps/src/Language/Marlowe/Runtime/App/Stream.hs
Changes in the underlying Runtime behavior resulted in a previously unreachable pattern match now being executed when payouts occur in a contract. Explicit handling on payout steps is added to gracefully deal with this case.
- Branch
- PR
> PLT-7288 Added handling of redemptions in contract streaming.

- marlowe-runtime/doc/resources.md
Updated Runtime's resource page, based on benchmarking v0.0.5 for sync times and resource usage.
- Branch
- PR
> PLT-7654 Re-benchmarked Runtime resources and syncing.

- marlowe-test/test/Spec/Marlowe/Semantics/Next.hs
- marlowe-test/test/Spec/Marlowe/Semantics/Next/Common/QuickCheck.hs
- marlowe-test/test/Spec/Marlowe/Semantics/Next/Contract.hs
There was an error and another error masking the first one:
- Invalid test cases were generated (this one was subtle and took me running `--quickcheck-tests 10000` to encounter.
- Shrinking broke invariants in the generator (tip: never do this: `forAllShrink myCustomGenerator shrink` - the shrink will likely destroy any invariants imposed by `myCustomGenerator`).
The primary issue was because of an inconsistency in the generator logic and the test logic. Some helper functions used in test case filtering failed to call `fixInterval`, and so some cases that passed the test case filtering failed the call to `next`. Notably:
```
( Environment {timeInterval = (POSIXTime {getPOSIXTime = -1},POSIXTime {getPOSIXTime = 0})}
, State
{accounts = Map {unMap = []}
, choices = Map {unMap = []}
, …
```
> PLT-7681 Applicability test for `Close` fails for Marlowe "next" semantics

- marlowe-protocols/changelog.d/20231016_154324_jhbertra_plt_8047_propagate_errors.md
- marlowe-protocols/marlowe-protocols.cabal
- marlowe-protocols/src/Network/Channel/Typed.hs
- marlowe-protocols/src/Network/Protocol/Connection.hs
- marlowe-protocols/src/Network/Protocol/Driver.hs
- marlowe-protocols/src/Network/Protocol/Driver/Trace.hs
- marlowe-protocols/src/Network/Protocol/Driver/Untyped.hs
> PLT-8047 propagate errors

- deploy/marlowe-runtime/values.yaml
This PR will disable temporarily the instances from QA, mainnet and preview networks.
The goal is to have only applications from demo-preprod running.
> chore: disable qa instances and preview/mainnet networks

- marlowe-chain-sync/deploy/indexAddresses.sql
- marlowe-chain-sync/libchainsync/Language/Marlowe/Runtime/ChainSync/Database/PostgreSQL.hs
- marlowe-chain-sync/revert/indexAddresses.sql
- marlowe-chain-sync/sqitch.plan
- marlowe-chain-sync/verify/indexAddresses.sql
- marlowe-runtime/changelog.d/20231107_140759_jhbertra_plt_8241_find_txs_for_performance.md
- nix/marlowe-cardano/compose.nix
> PLT-8241 find txs for performance

- deploy/marlowe-runtime/templates/marlowe-proxy.yaml
- deploy/marlowe-runtime/templates/marlowe-web-server.yaml
- deploy/marlowe-runtime/values.yaml
This PR prepares marlowe-cardano for EKS cluster migration.
Changes:
1. Adding some annotations on marlowe-proxy LoadBalancer as they are needed to create public instances of Network Load Balancer (they are private by default);
2. Removing opentelemetry-collector trait from marlowe-web-server, it's not needed anymore;
3. Changing DB hostname (New RDS instance is already synced);
IMPORTANT: Making it a Draft because we only need to merge it on main when the DNS switch is completed. These changes are already published on the new EKS cluster.
> infra: cluster migration

- flake.lock
- flake.nix
- marlowe-test/changelog.d/20231121_080323_brian.bush_PLT_8148_plutus1_15_0_0_validator.md
- marlowe-test/src/Spec/Marlowe/Plutus/Arbitrary.hs
- nix/marlowe-cardano/scripts.nix
Updates the validators used by `marlowe-cardano` (but not the script registry) to the Plutus v1.15.0.0 ones available on the PLT-8148 branch of `marlowe-plutus`.
- Branch
- PR
> PLT-8704 PLT-8148 Upgrade validators to Plutus v1.15.0.0

- marlowe-chain-sync/gen/Language/Marlowe/Runtime/ChainSync/Gen.hs
- marlowe-chain-sync/marlowe-chain-sync.cabal
- marlowe-chain-sync/src/Language/Marlowe/Runtime/ChainSync/Api.hs
- marlowe-integration-tests/test/Language/Marlowe/Runtime/Integration/Create.hs
- marlowe-integration-tests/test/Language/Marlowe/Runtime/Web/Contracts/Contract/Post.hs
- marlowe-runtime-web/.golden/OpenApi/golden
- marlowe-runtime-web/server/Language/Marlowe/Runtime/Web/Server/DTO.hs
- marlowe-runtime-web/src/Language/Marlowe/Runtime/Web/Types.hs
- marlowe-runtime-web/test/Spec.hs
- marlowe-runtime/changelog.d/20231124_083940_jhbertra_plt_8712_minting_metadata_additional_props.md
- marlowe-runtime/gen/Language/Marlowe/Runtime/Transaction/Gen.hs
- marlowe-runtime/marlowe-runtime.cabal
- marlowe-runtime/test/Language/Marlowe/Runtime/Transaction/ApiSpec.hs
- marlowe-runtime/tx-api/Language/Marlowe/Runtime/Transaction/Api.hs
- Added support for additional properties to role token metadata.
- Branch
- PR
> PLT-8712 Add support for additional properties on token metadata

- .github/workflows/deploy.yml
https://input-output.atlassian.net/browse/PLT-8402
Autodeploy to Kubernetes on push.
This PR adds a Github workflow similar to what currently exists in https://github.com/input-output-hk/marlowe-token-plans and https://github.com/input-output-hk/marlowe-playground/ for updating the values.yaml of the helm chart with the correct image tag and auto-committing, causing a deployment in KubeVela.
The `qa` environments track the latest commit. The `demo` environments are updated when a new version is tagged.
- Branch
- PR
> PLT-6842 Autodeploy on push

- deploy/marlowe-runtime/Chart.yaml
- deploy/marlowe-runtime/templates/chain-indexer.yaml
- deploy/marlowe-runtime/templates/chain-sync.yaml
- deploy/marlowe-runtime/templates/marlowe-contract.yaml
- deploy/marlowe-runtime/templates/marlowe-indexer.yaml
- deploy/marlowe-runtime/templates/marlowe-proxy.yaml
- deploy/marlowe-runtime/templates/marlowe-sync.yaml
- deploy/marlowe-runtime/templates/marlowe-tx.yaml
- deploy/marlowe-runtime/templates/marlowe-web-server.yaml
- deploy/marlowe-runtime/values.yaml
This PR introduce the changes below:
1.  Adds the capability of using one database instance per instance
2. Change all the QA networks to use a RDS instance restored before the last cluster migration attempt
3. Update otelExporter URL
> bump helm chart and using restored rds on QA

- deploy/marlowe-runtime/values.yaml
This PR introduces the change below:
1. Change all the Demo networks to use a RDS instance restored before the last cluster migration attempt
> using restored rds on Demo

- deploy/marlowe-runtime/templates/chain-indexer.yaml
- deploy/marlowe-runtime/templates/chain-sync.yaml
Increasing resources.cpu (Requests/Limits) for indexer deployments to avoid `CPUThrottlingHigh` alerts.
> chore: increase cpu resource for indexer deployments

- deploy/marlowe-runtime/templates/marlowe-contract.yaml
This trait will introduce a change on `marlowe-contract` update strategy, instead of create a new pod before terminating an old one (Default policy, `RolloutUpdate`), it will terminate the old one before creating a new one (`Recreate` strategy). 
It is needed because with the default policy, the new pods are stuck in `ContainerCreating` waiting for the EBS volume allocation.
> chore: adding k8s-update-strategy trait on marlowe-contract template

- marlowe-cli/changelog.d/20231215_114608_brian.bush_issue189.md
- marlowe-cli/command/Language/Marlowe/CLI/Command/Template.hs
The token for the Marlowe CLI swap contract now defaults to ada if not specified.
- Branch
- PR
> Fixed #189. Allow ada as default token for `marlowe-cli template swap`.

- marlowe-cli/changelog.d/20231215_115221_brian.bush_issue245.md
- marlowe-cli/src/Language/Marlowe/CLI/Run.hs
As noted in #245, `marlowe-cli run withdraw` erroneously includes a validity interval in the transaction. Although that was mostly harmless, it was unnecessary, so this PR removes it.
- Branch
- PR
> Fixed #245. Remove validity interval from `marlowe-cli run withdraw`.

- marlowe-runtime/tx/Language/Marlowe/Runtime/Transaction/Safety.hs
- marlowe-test/src/Spec/Marlowe/Reference.hs
- marlowe-test/test/Spec/Marlowe/Semantics/Compute.hs
- marlowe-test/test/Spec/Marlowe/Semantics/Functions.hs
- marlowe-test/test/Spec/Marlowe/Semantics/Golden/Tests.hs
- marlowe/src/Language/Marlowe/Analysis/Safety/Transaction.hs
- marlowe/src/Language/Marlowe/FindInputs.hs
Because we want to use analysis during input application I was forced to a bit update the API and expose possibility to work with preexisting state to generate valid inputs.
- Branch
- PR
> Accept `State` in the `getAllInputs` and `findTransactions` API

- marlowe-cli/cli-test/Language/Marlowe/CLI/Test/CLI/Interpret.hs
- marlowe-cli/cli-test/Language/Marlowe/CLI/Test/Interpret.hs
- marlowe-cli/cli-test/Language/Marlowe/CLI/Test/Runner.hs
- marlowe-cli/cli-test/Language/Marlowe/CLI/Test/Wallet/Interpret.hs
- marlowe-cli/command/Language/Marlowe/CLI/Command/Contract.hs
- marlowe-cli/command/Language/Marlowe/CLI/Command/Role.hs
- marlowe-cli/command/Language/Marlowe/CLI/Command/Transaction.hs
- marlowe-cli/marlowe-cli.cabal
- marlowe-cli/src/Language/Marlowe/CLI/Analyze.hs
- marlowe-cli/src/Language/Marlowe/CLI/Cardano/Api/PlutusScript.hs
- marlowe-cli/src/Language/Marlowe/CLI/Export.hs
- marlowe-cli/src/Language/Marlowe/CLI/Run.hs
- marlowe-cli/src/Language/Marlowe/CLI/Sync.hs
- marlowe-cli/src/Language/Marlowe/CLI/Transaction.hs
- marlowe-cli/src/Language/Marlowe/CLI/Types.hs
- marlowe-runtime/marlowe-runtime.cabal
- marlowe-runtime/test/Language/Marlowe/Runtime/Core/ScriptRegistrySpec.hs
- marlowe/changelog.d/20240103_105823_jhbertra_plt_8805_embed_validators.md
- marlowe/marlowe-cardano.cabal
- marlowe/src/Language/Marlowe/Scripts.hs
- marlowe/src/Language/Marlowe/Scripts/Types.hs
> PLT-8805 Embed Validators

- cabal.project
- marlowe-benchmark/LICENSE
- marlowe-benchmark/NOTICE
- marlowe-benchmark/ReadMe.md
- marlowe-benchmark/app/Language/Marlowe/Runtime/Benchmark.hs
- marlowe-benchmark/app/Language/Marlowe/Runtime/Benchmark/BulkSync.hs
- marlowe-benchmark/app/Language/Marlowe/Runtime/Benchmark/HeaderSync.hs
- marlowe-benchmark/app/Language/Marlowe/Runtime/Benchmark/Query.hs
- marlowe-benchmark/app/Language/Marlowe/Runtime/Benchmark/Sync.hs
- marlowe-benchmark/app/Main.hs
- marlowe-benchmark/changelog.d/20240104_144839_brian.bush_PLT_9014.rst
- marlowe-benchmark/marlowe-benchmark.cabal
This PR provides configurable volume/load tests for the following Marlowe Runtime protocols:
- `BulkSync`
- `HeaderSync`
- `Sync`
- `Query`
See https://github.com/input-output-hk/marlowe-cardano/tree/PLT-9014/marlowe-benchmark#readme for documentation and example output.
Subsequent PRs will address other protocols and data management for reporting.
- Branch
- PR
> PLT-9014 Query volume benchmarking for Marlowe Runtime

- marlowe-chain-sync/marlowe-chain-indexer/Options.hs
- marlowe-runtime/changelog.d/20240118_120513_jhbertra_decrease_indexer_batching.md
- nix/marlowe-cardano/deploy/operables.nix
Not confirmed - test will be to deploy and compare memory usage by `qa` to `0.0.6` mainnet instances.
- Branch
- PR
> Fix chain-indexer memory issues.

- marlowe-cli/changelog.d/20240119_111928_tomasz.rybarczyk_PLT_9308.md
- marlowe-cli/marlowe-cli.cabal
- marlowe-cli/src/Language/Marlowe/CLI/Analyze.hs
- marlowe-cli/tests/Spec/Analysis.hs
> Use provided state when running safety analysis  (PLT-9308)

- deploy/marlowe-runtime/Chart.yaml
- deploy/marlowe-runtime/templates/chain-indexer.yaml
- deploy/marlowe-runtime/templates/chain-sync.yaml
- deploy/marlowe-runtime/values.yaml
This PR introduce an update to helm templates from `marlowe-runtime`, allowing instances to select which service of `cardano-node` they will use. 
Right now we have:
1. `cardano-node`  running on version 8.4.0
2. `cardano-node-873` running on version 8.7.3
> chore: allow QA instance to use cardano-node-873

- flake.lock
- flake.nix
- marlowe-runtime/changelog.d/20240312_114424_nicolas.henin.md
- nix/marlowe-cardano/cardano-tools.nix
- nix/marlowe-cardano/compose.nix
This PR allows an owner of an aarch64 based computer (Mac ) to build/run and deploy locally this repository in a linux VM.
> Add support for aarch64-linux
